### ISSUE TITLE
Mocking credencial using file

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps-cli#103]
**Is your feature request related to a problem? Please describe.**

I have to enter credencial every time when verify auth.

**Describe the solution you'd like**

I want to mock credencial using a file.

**Describe alternatives you've considered**

Register multiple credencial at once in the UI. However, this is not the root solution.

**Additional context**

none

**Comment by manekinekko** [comment]
Thank you @k-miyake for suggesting this feature. 
That's something we could add to the config file https://github.com/Azure/static-web-apps-cli/issues/20

@anthonychu any thoughts on this?

**Comment by adrianhall** [comment]
We need more information about what is required here.  If the custom auth isn't working for you, please let us know why and how it would change?
