### ISSUE TITLE
add support for purging auth info

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#108]
Add support for deleting user auth info:
- [ ] `/.auth/purge/<AUTHENTICATION_PROVIDER_NAME>`
- [ ] `/.auth/purge/<AUTHENTICATION_PROVIDER_NAME>` 

See https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization#remove-personal-identifying-information

**Comment by anthonychu** [comment]
I think this is probably going to be just an alias to /.auth/logout

**Comment by santoshyadavdev** [comment]
Going to try this out.

**Comment by santoshyadavdev** [comment]
Hi @manekinekko few questions,
The endpoints mentioned should be called when we click logout in the app right?
Also the endpoints should be relative to the current URL, for eg:  http://localhost:4200/.auth/purge/<AUTHENTICATION_PROVIDER_NAME>

Let me know if my assumption is correct.

**Comment by manekinekko** [comment]
> The endpoints mentioned should be called when we click logout in the app right?

If the developer adds these routes in their application, then yes, they'd be called when the user clicks on them.

So by design the SWA CLI doesn't support Auth locally. We provide an emulated mode for Auth when you access `/.auth/login/<provider>`. Then we only propagate the cookies in all requetes. 

As @anthonychu mentioned, for now, I think we can simply add these purge requests as aliases for the logout route, in this array: 

https://github.com/Azure/static-web-apps-cli/blob/23699329b607fca74789d6b27d950d5562bc9089/src/auth/index.ts#L4-L20

**Comment by santoshyadavdev** [comment]
I am using windows and dont have installed azure-functions-core-tools, while running the `swa start` I am getting below error:

![image](https://user-images.githubusercontent.com/11923975/115121203-fbb5b100-9fce-11eb-95c2-0c82dbe3aadc.png)
As per doc, it is optional, I am installing azure-functions-core-tools to check if it is the one causing the issue.

**Comment by manekinekko** [comment]
From your screenshot it looks that you have a space in your path "SWA CLI".

Are you able to send a PR to fix this? The fix would be to wrap the path with `"   "` in these lines:

https://github.com/Azure/static-web-apps-cli/blob/16c4f35df8191f0ffd87c1ee82e52061b909e736/src/cli/commands/start.ts#L82

Here:
https://github.com/Azure/static-web-apps-cli/blob/16c4f35df8191f0ffd87c1ee82e52061b909e736/src/cli/commands/start.ts#L124

And here:
https://github.com/Azure/static-web-apps-cli/blob/16c4f35df8191f0ffd87c1ee82e52061b909e736/src/cli/commands/start.ts#L137

**Comment by santoshyadavdev** [comment]
Yes sure, will do that.

**Comment by manekinekko** [comment]
@santoshyadavdev did you have a chance to work on the PR?

**Comment by santoshyadavdev** [comment]
Sorry for delay here the changes you suggested worked, need to add tests, will do over the weekend, just to understand on Testing part, it will be a E2E test to check npm start command right?

**Comment by manekinekko** [comment]
@santoshyadavdev don't worry about the tests. I will add those. That's part of another task. Thanks buddy ❤️

**Comment by santoshyadavdev** [comment]
> @santoshyadavdev don't worry about the tests. I will add those. That's part of another task. Thanks buddy ❤️

Great then I will push the changes tomorrow 😊
