### ISSUE TITLE
Consolidate logging information to the console.

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#111]
As SWA CLI user, I'd like to be able to have the following information printed by the CLI:
- [x] the CLI server address ([feedback](https://github.com/Azure/static-web-apps-cli/issues/88#issuecomment-797014153) from @nturinski)
- [ ] the app production URL (inferred from the GA workflow)
- [x] GA workflow file (if found)
- [x] swa config (or routes.json) file (if found)
- [x] information about the request (method, path)
- [x] information about the response (statusCode, ...)
- [ ] applied config rules?

@anthonychu any other useful information we need to log to the console?

**Comment by johnpapa** [comment]
yes! I was about to add this! Colored and with white space please

**Comment by johnpapa** [comment]
I wonder if we can reduce this, notice the API calls. Really nothing valuable there other than "Executing products-get" and duration, ya know? And in the second image, you can see all the "cant determine project language" stuff we've talked about


![image](https://user-images.githubusercontent.com/1202528/110986866-38411d80-833c-11eb-996e-ee9a82185dcc.png)



![image](https://user-images.githubusercontent.com/1202528/110986887-40995880-833c-11eb-93e7-c6ea08a39c3e.png)

**Comment by manekinekko** [comment]
I agree.

@anthonychu do we have control over the `func` output? Can we override the user's setting from the `func` CLI to eliminate these logs?

**Comment by manekinekko** [comment]
@johnpapa @nturinski @anthonychu  what do you guys think about this first iteration?

### Standalone

`swa start angular-app/dist/angular-app`

![image](https://user-images.githubusercontent.com/1699357/111014471-154a5400-83a4-11eb-98c0-6ca352d12048.png)

### Dev Server

`swa start http://localhost:4200`

![image](https://user-images.githubusercontent.com/1699357/111014498-37dc6d00-83a4-11eb-816b-e2f124e61c3c.png)

### Errors...

![image](https://user-images.githubusercontent.com/1699357/111014526-55a9d200-83a4-11eb-87b3-c811f3dd5387.png)

![image](https://user-images.githubusercontent.com/1699357/111014554-72dea080-83a4-11eb-9e6a-6a8897933891.png)

![image](https://user-images.githubusercontent.com/1699357/111014618-dcf74580-83a4-11eb-91d8-d2e17f0dc488.png)

### API

We need to figure out how to silent the `func`.

![image](https://user-images.githubusercontent.com/1699357/111014647-ff895e80-83a4-11eb-98a5-74b5047db9d6.png)

**Comment by anthonychu** [comment]
What output from func do you want to suppress? Those warnings are because local.settings.json are missing. We could update func to only print it once.

**Comment by manekinekko** [comment]
I think John was referring to all output. But I'd love if we can filter out the logs we wanna show or hide. I guess that m

**Comment by anthonychu** [comment]
I think it's important to keep some of the function app logging and we should keep it the way it is for now. Main concern here is if we hide too much, it's hard to tell what's going on and people end up raising support tickets.

**Comment by sinedied** [comment]
@manekinekko The new proposed output looks nice, I have 2 comments though

- I think it would be nice to have a less verbose output by default, not sure I need to know every request that goes by, only those that resulted in an error. A `--verbose` option could be used to show all the details.
- The prefixes `[swa]`,` [api]` clutters the output IMHO, by default I would prefer a simpler view without any prefixes.

**Comment by johnpapa** [comment]
I appreciate the feedback y'all have left here and I agree that some logging is important to keep as @anthonychu write and also that the prefixes seem to clutter a little, as @sinedied  wrote. I also feel that the right balance of bth of these is probably what is needed and we're all trying to find. 

1. remove the colors from the prefixes. colors make it stand out and I'm not sure we need every line to stand out.
2. maybe then the prefixes will be less clutter and still be helpful. I like the knowing where it came from, jst don;t want it highlighted too much
3. the `verbose` flag is a great ida. Can it work on functions the same way functions verbose works , for consistency?
4. the URL that launch (ex: **http://0.0.0.0:4280**) gets lost in the output. I think there are a few reasons for this. It's shown early and the API's have a lot of output and are always shown after. Could we show the URL 2nd to last ?
5. Can we add a success message as the final output and highlight the message in green?

I would default to showing the API calls (as we do today). I do like seeing them as they are helpful and give the customer a sense for the Functions activity. If they werent there I wonder if people would be confused if they are running. 

Perhaps default them to showing and have a flag for hiding them?

**Comment by manekinekko** [comment]
Thank you all. Based on your feedback I've update the `--verbose` flag to accept the following options:

    - log    : print basic information (default)
    - info   : print more information
    - silly   : print everything (also sets DEBUG=*)
    - error : print errors only
    - silent: don't print any logs nor errors

### `--verbose=log`
![image](https://user-images.githubusercontent.com/1699357/111391638-53ea5200-86b5-11eb-8889-98fa7186ed5b.png)

### `--verbose=info`
![image](https://user-images.githubusercontent.com/1699357/111391989-fc98b180-86b5-11eb-9dda-0a44d9ec5000.png)

### `--verbose=silly`
![image](https://user-images.githubusercontent.com/1699357/111392088-3073d700-86b6-11eb-9c32-9276eb5e3014.png)

### `--verbose=error`
![image](https://user-images.githubusercontent.com/1699357/111392132-42ee1080-86b6-11eb-803d-43a0cc0b88a9.png)

### `--verbose=silent` (for @sinedied 😂)
![image](https://user-images.githubusercontent.com/1699357/111392186-56997700-86b6-11eb-818e-845cf5029423.png)


@anthonychu once you approve #127 I'll merge it and we can cut a new release.
