### ISSUE TITLE
CTRL-C took 2 minutes to apply

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps-cli#112]
**Describe the bug**
CTRL-C many times does not close the running process, for about 2 minutes

**To Reproduce**
1. Using the shopathome monorepo, run the `swa start` in the root
2. CTRL-C many times
3. 

**Expected behavior**
Should kill the process right away

**Additional context**
![image](https://user-images.githubusercontent.com/1202528/110968679-d37ac880-8325-11eb-9ec2-f28a776443bd.png)

**Comment by manekinekko** [comment]
Interesting! I am unable to reproduce this. 
![image](https://user-images.githubusercontent.com/1699357/110975111-97fcf000-835f-11eb-870b-737b30e80b0c.png)

I see a GET request there, have you tried to access the app from a browser before killing the process?

**Comment by johnpapa** [comment]
I did refresh web page once.

**Comment by anthonychu** [comment]
I've run into this on macOS a couple of times.
