### ISSUE TITLE
Auto-Gen the User ID, and Don;t show to the user

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps-cli#113]
For auth, is asking the user to enter a user ID confusing? This User id appears to be an Azure thing (a principal). I think we're asking for something locally that Azure generates for you when you do it in the portal. Will the customer know what that is?  Should they?

Could we generate a random value and not prompt the user? Also, Is there any reason to show this?
![image](https://user-images.githubusercontent.com/1202528/110987056-8b1ad500-833c-11eb-83e0-2912415f65bd.png)

**Comment by manekinekko** [comment]
Great suggestion @johnpapa !

Here is what I suggest:
- we generate a random ID (following the same Az pattern)
- we keep that field visible but we disable it (like we do for the provider).

Wdyt?

**Comment by johnpapa** [comment]
I like that.

I admit, I was completely confused. I have been using values like Fred and Sally in it:)
