### ISSUE TITLE
Cannot start index.html with `script type="module"`

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps-cli#119]
**Describe the bug**

Using the `0.1.1-alpha` SWA CLI, 
`<script type="module" ... >` with js files loaded in `index.html` with SWA CLI, the following execution error occurs.

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**
1. build vue.js app using [vite](https://vitejs.dev/)
2. swa start ./dist (using `0.1.1-alpha` swa cli)
3. Index.html is not rendered and the following error is displayed in the browser console

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Expected behavior**
index.html will be rendered

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89.0.4389.82

**Additional context**
The application that is built by [vite](https://vitejs.dev/) using esbuild, so that may be the cause.

**Comment by manekinekko** [comment]
Hi @k-miyake Our npm is a little bit outdated. We will cut a new release next week.

Would you mind trying the package from the `main` branch? using the command:

```
npm install -g https://github.com/Azure/static-web-apps-cli.git#main
```

**Comment by k-miyake** [comment]
@manekinekko Thank you.
I installed the command from the main branch using the method you advised and had the same situation.
I'll wait for next week's release.

**Comment by manekinekko** [comment]
Hey @k-miyake I can't reproduce the issue. Could you please try again with the latest code from `main`?

![image](https://user-images.githubusercontent.com/1699357/111309633-6a17f400-865c-11eb-8f6c-1ba88eee8be6.png)

**Comment by k-miyake** [comment]
@manekinekko I updated the SWA CLI to `0.2.0` -> `0.2.1-alpha` and Vite to `2.0.5` -> `2.1.0` and it worked! 
Thanks for the quick response! 
I'll demo it at Azure local event next week!

**Comment by manekinekko** [comment]
That's awesome! Let's know how it went ☺️

Good luck!
