### ISSUE TITLE
Add flag to accept location of config or routes.json

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#125]
When using a dev server (`swa start http://localhost:3000`) or when serving static files from a folder that doesn't contain staticwebapp.config.json (`swa start ./dist`), allow the location of the config/routes file to be specified from the CLI.

Should be able to specific the path to the file, or the folder containing the file (if both staticwebapp.config.json and routes.json exist, use staticwebapp.config.json).

We should also ensure the current behavior of how the files are found are properly documented.

**Comment by manekinekko** [comment]
Currently, the CLI looks for the `staticwebapp.config.json` or `routes.json` from the root of `appLocation` and crawls all folders to find those files. If both files are found, `staticwebapp.config.json` will be used.

Should we change this behavior @anthonychu ?

**Comment by anthonychu** [comment]
Yeah. Maybe I need to understand more about how the file discovery logic works. There’s no app_location if proxying to a dev server. I guess one can be inferred if we can find a GitHub action workflow. But I then would like to understand what happens if there are more than one workflow (like in a monorepo).

**Comment by manekinekko** [comment]
Here is how we currently process the start command...

- start cli with a context `swa start <context>`
- if `<appContext>` is local folder and exists:
  - set `appArtifactLocation = appContext`
   - look for SWA workflow files under `<appLocation>/.github/workflow/**.yml` (use 1st file for the moment - see #32).
   - merge CLI config with workflow config (CLI takes precedence)
   - look for user's config custom rules  under `<appLocation>` (`staticwebapp.config.json` or legacy `routes.json`).
   - run proxy and provide user's config
   - serve local static content

- if `<appContext>` is HTTP dev server:
  - set `appArtifactLocation = context`
  - check if dev server is up and running.
  - skip workflow files and user's config custom rules.
  - run proxy
  - forward static content (not `/.auth/ and not /api/`) requests to app dev server

- if `--api=<apiContext>` is provided:
  - set `apiLocation = apiContext`
  - if `apiLocation` is local folder and exists:
     - look for SWA workflow files under `<appLocation>/.github/workflow/**.yml` (use 1st file for the moment - see #32).
     - merge CLI config with workflow config (CLI takes precedence)
     - run `func` and serve `/api/**` queries
  - if `apiLocation` is HTTP dev server:
     - run proxy
     - forward `/api/` to api dev server
