### ISSUE TITLE
Error when defining Fallback routes

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps-cli#126]
**Describe the bug**
Using the 0.2.0 SWA CLI,
when put the Fallback routes in config, initial screen created Vue.js is not rendered and getting an error in the browser console.

defined fallback routes following in ` staticwebapp.config.json`.

```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/img/*.{png,jpg,gif}", "/css/*"]
  }
}
```

**To Reproduce**
1. Build the Vue application with `npm run build`
2. Run `swa start ./dist`
3. Index.html is not rendered and the following error is displayed in the browser console

```
Uncaught SyntaxError: Unexpected token '<'
```

**Expected behavior**
index.html will be rendered

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.82

**Additional context**
SWA CLI is 0.2.0 installed via npm

**Comment by manekinekko** [comment]
Hey @k-miyake the fallback should match how your application is served. In you case, the `fallback` rule should look like:

```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/js/*.{js,map}", "/css/*.{css}"]
  }
}
```

You need to update the exclusion rule so that all Vue.js javascript file and css can be served and not blocked. Let me know if that's clear.

![image](https://user-images.githubusercontent.com/1699357/111138325-16d07380-8580-11eb-9240-a3914ac48645.png)

**Comment by k-miyake** [comment]
@manekinekko Thanks! The settings you wrote solved the problem.
I was confused because the configuration has changed since `routes.json`.

**Comment by k-miyake** [comment]
@manekinekko The `navigationFallback` now works, but rewrite and redirect no longer work correctly.
For example, if access `http://localhost:4280/login`, get a blank screen. The settings for `routes` are as follows.

```json
{
  "routes": [
    {
      "route": "/admin/*",
      "allowedRoles": ["admin"]
    },
    {
      "route": "/login",
      "rewrite": "/.auth/login/github"
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": 404
    },
    {
      "route": "/logout",
      "redirect": "/.auth/logout"
    }
  ],
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/js/*.{js,map}", "/img/*.{png,jpg,gif}", "/css/*"]
  }
}
```

**Comment by manekinekko** [comment]
Thank you @k-miyake I will investigate that.
