### ISSUE TITLE
Definitive output for when the SWA and API are running and available

### ISSUE THREAD

**Issue by nturinski** [Azure/static-web-apps-cli#142]
This is largely to support tasks in VS Code.  Specifically, if we had output that we can match to signify the end of the `swa start` task, it would make creating the launch and task jsons a little bit cleaner.

For example, today I am waiting on `"Host lock lease acquired` but this only applies if I have an api in my project.  Without an api, `serving * at http://0.0.0.0:4280` would be end output.

In both cases, I am running the start command with the output and api locations specified in the `start` command rather than starting the `dev server` and the `func host start` processes first, and attaching the emulator to those addresses.

**Comment by anthonychu** [comment]
Does the current output from #124 suffice? Feel free to suggest something that would work better.

@manekinekko Probably should add to the startup tests that we plan to write to ensure this output remains the same.

**Comment by manekinekko** [comment]
That's the message we currently output. However, I noticed when we also spawn the API server, it obviously takes more time to start (as you can see from the screenshot). Would that be a problem @nturinski ?

Also, as @anthonychu mentioned, feel free to let me know if the message we output does the job for you or we can add a different marker?

![image](https://user-images.githubusercontent.com/1699357/112447588-ca402180-8d51-11eb-87f6-aaab04ce1e68.png)

**Comment by nturinski** [comment]
Yeah, you nailed it.  For VS Code, we would want to launch the debugger only after the API server is done spawning (if they have one).  

Though now that I think about it, it should be fine to listen for `Azure Static Web Apps emulator started` for one task and `Host lock lease acquired` for another since we'll probably have to define two separate tasks for users anyway (one with API and one without). 

I think my preference would be if we could move `Azure Static Web Apps emulator started` down below once everything is running and available, but if that causes issues, no need to change anything.

**Comment by manekinekko** [comment]
@nturinski so currently we start the emulator in one process, and then start the API (if provided) in a different process. The two processes don't communicate together. Right now, the emulator has no idea when the API is ready or not. To do that I will have add some logic and await for the API to boot before spawning the emulator. It should be doing in a day.

Do you need me to explore this option? @anthonychu wdyt?

**Comment by nturinski** [comment]
Nah, I don't think it'll be necessary.  Thanks for all the info!
