### ISSUE TITLE
Azure static apps CLI : Cannot get it working with Angular App

### ISSUE THREAD

**Issue by sajeetharan** [Azure/static-web-apps-cli#166]
**Describe the bug**
I am not exactly sure if this is a bug. But i have a simple angular application and i installed the CLI for static web apps. When i tried to do a local build with the output path i am getting the below error!

![image](https://user-images.githubusercontent.com/4833351/113810469-f57e3400-9787-11eb-866f-50e094e7e0e4.png)

**To Reproduce**
1. Created an angular app
2. Did a local build using ng build
3. Executed the swa command

**Expected behavior**
 
 
**Additional context**

**Comment by anthonychu** [comment]
@sajeetharan What version of Node are you using?

**Comment by sajeetharan** [comment]
@anthonychu  i found that i was using v10.16.0, now i upgraded to v14.16.1 . 

![image](https://user-images.githubusercontent.com/4833351/113828404-f754f100-97a1-11eb-9988-188334f2a06d.png)

when i access http://localhost:4280/ it says it cannot get!

**Comment by manekinekko** [comment]
@sajeetharan if you are using Angular, then by default your static assets should be under `./dist/<angular-app>/`.

Also, interesting to see that we could not bind to your LAN IP address. Do you have any special setup?

**Comment by manekinekko** [comment]
@anthonychu  we should probably mention in the README that we only support node 12 and latest.

**Comment by sajeetharan** [comment]
@manekinekko Yeah with the latest version app is running, but it does not get the default page loaded, i don't have any special setup. can you be specific? i am running on windows 10 and using windows terminal

**Comment by manekinekko** [comment]
>  but it does not get the default page loaded,

What do you see when you access [http://0.0.0.0:4280](http://0.0.0.0:4280)?

> i don't have any special setup. can you be specific

the CLI is supposed to capture and bind to your local LAN IP:
![image](https://user-images.githubusercontent.com/1699357/113879484-d8168d80-97ba-11eb-84cb-c90e4a7a958f.png)

In your screenshot I see `http://undefined:1234` which is not good. I need to investigate this.

**Comment by manekinekko** [comment]
Interesting! Can you please share your repo (if it's public)? Or a screenshot of the content of your dist/<app> folder?

**Comment by sajeetharan** [comment]
@manekinekko  Here is the repo https://github.com/sajeetharan/meme4fun

**Comment by manekinekko** [comment]
@sajeetharan I could not reproduce the issue you're having with your repo. When start the CLI, I can access to your app:

Here are the steps I followed:

```
git clone git@github.com:sajeetharan/meme4fun.git
cd meme4fun
npm install
npm run build
swa start dist/meme4fun
```
![image](https://user-images.githubusercontent.com/1699357/113920293-e083be00-97e4-11eb-914c-9e05918c4985.png)

![image](https://user-images.githubusercontent.com/1699357/113920105-a87c7b00-97e4-11eb-9fc1-833b282f773a.png)

**Comment by sajeetharan** [comment]
Thanks @manekinekko i cloned it again and tried, seems to be working fine.

I think the mistake i made was without mentioning the path i just ran 

`swa start`

**Comment by manekinekko** [comment]
Glad to hear it's working. Yeah, `swa start` is an alias to `swa start  ./` which will start the server from the current folder.
