### ISSUE TITLE
Rename --routes-location

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#175]
**Is your feature request related to a problem? Please describe.**
Config file no longer called routes.json. We should call this something else.

**Describe the solution you'd like**
Maybe `--config-location`? Is it confusing if we have a CLI config too #20?

**Comment by manekinekko** [comment]
Naming is hard! What about?

- `--cli-config-location`: for the CLI config
- `--swa-config-location`: for staticwebapp.config.json

**Comment by anthonychu** [comment]
Ok. I think that works. It's unclear if one day we'll need to specify the CLI config too (probably). If that's the case, `swa-config-location` works. 😅
