### ISSUE TITLE
Apply config when running dev server

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#176]
**Is your feature request related to a problem? Please describe.**
When running a dev server, config like rewrites, authorization are not applied.

**Describe the solution you'd like**
Apply config even when running dev server
* staticwebapp.config.json in current directory: `swa start http://localhost:8080`
* staticwebapp.config.json elsewhere: `swa start http://localhost:8080 --routes-location web` (or whatever the option is eventually named #175)

Config should apply to function app routes as well.

**Comment by manekinekko** [comment]
> staticwebapp.config.json in current directory: swa start http://localhost:8080

This can be easily fixed by removing this check:
https://github.com/Azure/static-web-apps-cli/blob/888bbcd5390e44924a3f30d8cbaffdd8473f5678/src/proxy/server.ts#L310-L312

**Comment by fgiuliani** [comment]
@anthonychu @manekinekko can I take a look here? Do you have some guidance for a first-issuer? 😂

**Comment by manekinekko** [comment]
Thank you @fgiuliani for offering your help. Please have a look at our [contributing guide](https://github.com/Azure/static-web-apps-cli/blob/main/CONTRIBUTING.md) in order to get started.

**Comment by manekinekko** [comment]
@fgiuliani We are planning to cut a minor release by end of week. Are you able to send a PR this week?

**Comment by fgiuliani** [comment]
Hi @manekinekko!
I'm able to work on this issue this week, but I think I need some guidance about the changes to be made. 
I was looking at the contributing guide and the code of the app and I'm not sure I get what has to be done.

Thank you for the help and sorry for bothering you!

**Comment by manekinekko** [comment]
Hey @fgiuliani we are going to refactor the proxy implementation (in #186) and this change will be affected. So we're gonna delay this feature for now.

**Comment by fgiuliani** [comment]
got it @manekinekko. Thank you!

**Comment by anthonychu** [comment]
This should be addressed in #208
