### ISSUE TITLE
404 pages will not be displayed with fallback routes in config

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps-cli#178]
**Describe the bug**
Vue.js app are served with 0.3.0 CLI.
When put the fallback routes in config, 404 page is not displayed.

Defined fallback routes following in ` staticwebapp.config.json`.

```json
{
    "navigationFallback": {
        "rewrite": "/index.html",
        "exclude": ["/js/*.{js,map}", "/img/*.{png,jpg,gif}", "/css/*"]
    }
}
```

**To Reproduce**
1. Build the Vue application with `npm run build`
2. Run `swa start ./dist`
3. Enter the URL of a path that does not exist, for example, `http://localhost:4280/abc`.
4. You will see a screen with nothing rendered.

**Expected behavior**
404 page will be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.114

**Additional context**
SWA CLI is 0.3.0 installed via npm

**Comment by manekinekko** [comment]
Thank you @k-miyake for creating this issue. it looks like this is a duplicate or related to #168 that I am already working on. Will keep you posted.

**Comment by manekinekko** [comment]
@k-miyake I tried your steps on a local Vue app and I can see my custom message. Can you share a screenshot of your issue?

![image](https://user-images.githubusercontent.com/1699357/114152796-f7c6c680-991e-11eb-8c3c-da549883840c.png)

**Comment by manekinekko** [comment]
btw, in my Vue router configuration, I've setup a custom 404 component:

```

export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
   ...
    {
      path: '*',
      component: PageNotFound,
    },
  ],
});

```

**Comment by k-miyake** [comment]
@manekinekko 
My explanation may have been bad.
I wanted to know how to get the default 404 page of the SWA CLI to show up, not the custom 404 page not showing up.
If you remove the fallback setting, the SWA CLI's 404 page will be displayed.
![404](https://user-images.githubusercontent.com/1104403/114157850-092fc300-995f-11eb-8d65-bb9c35147605.png)

**Comment by k-miyake** [comment]
@manekinekko 
I realized that since it's an SPA, it's impossible to display the SWA 404 page as long as I set a fallback.
I'll wait for the #168 fix and use custom 404.
Thanks.

**Comment by manekinekko** [comment]
Fixed by https://github.com/Azure/static-web-apps-cli/pull/179. @k-miyake  can you confirm it's working for you as expected?

**Comment by k-miyake** [comment]
@manekinekko
I installed CLI from main branch, and the 404 page is displayed, but fallback does not work.
