### ISSUE TITLE
Improve routes engine

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#186]
This issue will track our efforts to improve the implementation of the routes engine.

@anthonychu I started a draft branch with few code changes: https://github.com/Azure/static-web-apps-cli/tree/issue-186

**Comment by anthonychu** [comment]
@manekinekko Thanks for creating the branch. Been trying to think about how the logic should work. Came up with the pseudocode below. Not sure how to change the existing code to match. Let me know if you have ideas.

```js
function handleRequest(req, res) {

    matchingRouteRule = getMatchingRouteRule(config, req)

    if (matchingRouteRule?.redirect) {
        createRedirectResponse(res, matchingRouteRule)
        return
    }

    if (isAuthUrl(req)) {
        createAuthResponse(req, res)
        return
    }

    if (!isAuthorized(req, matchingRouteRule)) {
        createUnauthorizedResponse(res)
        return
    }

    if (matchingRouteRule.rewrite) {
        req.url = matchingRouteRule.rewrite
    }

    serve(req, res, matchingRouteRule)

    if (isApiUrl(req)) {
        return
    }

    if (res.status === 404 && hasNavigationFallback(config)) {
        if (!isExcluded(config.navigationFallback, req)) {
            if (config.navigationFallback.rewrite) {
                fallbackRequest = config.navigationFallback.rewrite
                serve(fallbackRequest, res, null)
                if (isApiUrl(fallbackRequest)) {
                    return
                }
            } else if (config.navigationFallback.redirect) {
                createRedirectResponse(res, config.navigationFallback)
                return
            }
        }
    }

    matchingResponseOverride = getMatchingResponseOverride(config, res)
    if (matchingResponseOverride) {
        if (matchingResponseOverride.rewrite) {
            overrideRequest = matchingResponseOverride.rewrite
            serve(overrideRequest, res, null)
            if (isApiUrl(overrideRequest)) {
                return
            }
        } else if (matchingResponseOverride.redirect) {
            createRedirectResponse(res, matchingResponseOverride)
            return
        }
    }

    if (matchingRouteRule?.headers) {
        applyHeaders(res, matchingRouteRule.headers)
    }

    if (config.globalHeaders) {
        applyHeaders(res.globalHeaders)
    }

    matchingMimeType = getMatchingMimeType(config, req)
    if (matchingMimeType) {
        applyContentTypeHeader(matchingMimeType, res)
    }


    function serve(req, res, matchingRouteRule) {
        if (isApiUrl(req)) {
            callApi(req, res)
        } else {
            if (isDevServer) {
                callDevServer(req, res)
            } else {
                createStaticFileResponse(req, res)
            }
        }
    }
}
```

**Comment by manekinekko** [comment]
I think the best option would be to rewrite bits of the proxy and routes engine. Do you need me to take care of that?

**Comment by anthonychu** [comment]
Yes. If you can that’d be great. Couldn’t figure out how to even get started without breaking all the tests!

**Comment by GeekTrainer** [comment]
Wanted to bump this one as I'm currently having an issue with routes set in the staticwebapp.config.json file being ignored.

Environment:
App created with Svelte-Kit, running via Vite.
Start script: `svelte-kit dev & swa start http://localhost:3000 --api ./api`

staticwebapp.config.json located in root (`./`):

``` json
{
    "routes": [
        {
            "route": "/api/login",
            "rewrite": "/.auth/login/github"
        }
    ]
}
```

Routes properly recognized on ASWA, but not when running the CLI

**Comment by anthonychu** [comment]
We're working on revamping the routing engine. It's significant work so we don't have an ETA right now. @GeekTrainer We should be addressing your scenario with these changes.

**Comment by GeekTrainer** [comment]
@manekinekko Was this resolved? I noticed the issue was closed.

Thanks!!

**Comment by manekinekko** [comment]
@GeekTrainer  the change landed in https://github.com/Azure/static-web-apps-cli/commit/16990e8e1e0d907e6e95381f5e9a155cebb74711. You can go ahead and download the latest version of SWA CLI. Also, please let us know if you are still having issues.
