### ISSUE TITLE
Add swa.json config file

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#20]
**Describe the solution you'd like**
As a user, I'd like to be able to start `swa` using a config file. All the CLI flags should be supported.

```json
{
  "options": {
   // CLI flags
  }
}
```

File name options:
- `swa.json`
- `swa.config.json`
- `.swarc`
- `swa` property in `package.json`

**Comment by manekinekko** [comment]
@k-miyake sorry about the confusion:
-  `staticwebapp.config.json` is the config file for your project deployed on SWA
- `swa.config.json` (this issue) is the config file for the CLI.

Do you have other suggestions for the CLI config file?

**Comment by k-miyake** [comment]
I was mistaken, sorry.
In this issue, discussing a different file than `staticwebapp.config.json`.

It is preferable to use a file name that indicates it is for development.
For example, `swa.development.json` or `local.development.json`.

**Comment by anthonychu** [comment]
For naming, thinking something like `swa-cli.config.json` so it's clear that it's for the CLI.

For contents, I think we can start with a single prop named `configurations` (not sure what else to name them, maybe `environments`? `contexts`?).

```jsonc
{
  "configurations": {
    "app1": {
      "context": "./static",
      "api": "./api"
    },
    "app2": {
      "context": "http://localhost:3000",
      "app-startup-command": "cd frontend && npm start", // proposed in #147
      "api": "./api"
    }
  }
}
```

If there's a single configuration, `swa start` can just use it.

If there's more than one, use `swa start app1`. If there's a folder of the same name, the CLI will prefer the config file.

If `swa start` is run without a context, perhaps use interactive prompts to create the file. (this is lower priority and can be a separate issue)

**Comment by alexweininger** [comment]
I really like this feature. I'm exploring adding local debugging for SWAs into the VS Code extension and this would make the configuration much easier on users.
