### ISSUE TITLE
Fill in the User ID for the user?

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps-cli#204]
Can we provide a User ID for the Auth for the user? It's not clear what we are supposed to fill in for that value and it is required.

**Comment by manekinekko** [comment]
Are you referring to this field? It seems that this value is populated by [SWA on production](https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#client-principal-data). But locally we are just generating a random UUID. 

![image](https://user-images.githubusercontent.com/1699357/118498584-7a188680-b726-11eb-844e-5c26d0b99f0d.png)

**Comment by johnpapa** [comment]
Yes, that box.

I updated to the latest version. Maybe because I had in during beta/pre-release ... but it often is empty for me.

**Comment by manekinekko** [comment]
Are you able to check the devtools to see what's the issue? Also, the latest version on npm should be `0.4.1-alpha`.

**Comment by Reshmi-Sriram** [comment]
Hi @johnpapa! 
It'd be great if you can confirm whether this issue still persists. If yes, could you try out the suggestions provided by @manekinekko? (P.S. the latest version on npm now should be `0.6.2-alpha`)
If no, we'll close this issue for the time being and you can always reopen it in case we need to look into this further! :)

**Comment by Reshmi-Sriram** [comment]
This issue should be resolved.
