### ISSUE TITLE
Static Web App with Blazor and AUTH config in staticwebapp.config.json without effect on SWA CLI

### ISSUE THREAD

**Issue by Azuredevmuc** [Azure/static-web-apps-cli#205]
**Describe the bug**
Thanks for all the work on this very nice tool! I like it a lot. But i experience a bug i guess.
By starting SWA using this command: ` swa start https://localhost:5001 --api Api --swa-config-location ./Client/wwwroot` , and f or sure previously startet `dotnet run watch` to have the server runniing.
My expactation would be: AUTH can be simulated.

**To Reproduce**
- use default Blazor SWA Demo repo
- configure route in staticwebapp.config.json and place it in ./Client/wwwroot like so:
 `{

  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/_framework/*", "/css/*", "*.{js,map,css,png,ico}"]
  },  
  "routes": [

      {
        "route":"/login",
        "redirect":"/.auth/login/aad"
      },
      {
        "route":"/fetchdata",
        "allowedRoles":["authenticated"]
      },
      {
        "route": "/.auth/login/twitter",
        "statusCode": "404"
      }
    ]
  }`
- start `dotnet run watch` on the client path
- start SWA CLI using this command: ` swa start https://localhost:5001 --api Api --swa-config-location ./Client/wwwroot`
- Navigate to "Fetch Data"

**Expected behavior**
- Expected result: page cannot be loaded, cause u r not loged in. but it loads.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - CLI 0.4.0

**Comment by horihiro** [comment]
This looks the same as https://github.com/Azure/static-web-apps-cli/issues/176
Currently swa-cli doesn't load `staticwebapp.config.json` when the dev server is specified.

**Comment by manekinekko** [comment]
@horihiro  is right. We currently don't load the `staticwebapp.config.json` when running a dev server. We are still experimenting with the best way to approach this. 

This is a planned feature. Stay tunned.

**Comment by Azuredevmuc** [comment]
Okay - thank you @horihiro  & @manekinekko ,
maybe this could be a note in the docu - cause i was really frustrated testing this.
Since this is also not working with VS Code extension for SWA - you are limited to do "live" tests :)

**Comment by manekinekko** [comment]
Thanks for the feedback @Azuredevmuc. We'll sync with our docs teams on this.

cc @craigshoemaker.

**Comment by Azuredevmuc** [comment]
@manekinekko , thanks.

**Comment by Azuredevmuc** [comment]
As part of my try to use AUTH with SWA and Blazor I learned, that i have to use Client-Side Navigation and there also AUTH.
So, to use Blazor with AUTH - this Article will help: 
https://anthonychu.ca/post/blazor-auth-azure-static-web-apps/
For anything affecting the server-side, the config will do.
May be, this helps others too.

**Comment by craigshoemaker** [comment]
I updated the note at the top of the page to read:

> The Azure Static Web Apps CLI is currently a preview feature and doesn't read configuration defined in the _staticwebapp.config.json_ file.

The change will go live in a few hours.

**Comment by anthonychu** [comment]
Tested the changes in #208 and it looks like this will be resolved by that PR! 🎉

**Comment by anthonychu** [comment]
#208 is merged and released in v0.5.0. Please reopen if issue persists.
