### ISSUE TITLE
Azure DevOps git repo via Azure CLI : Command group 'staticwebapp' is in preview and under development.

### ISSUE THREAD

**Issue by sajeetharan** [Azure/static-web-apps-cli#207]
**Describe the bug**
I came across this question in a forum on how to deploy a react application to Azure static web apps with Azure Devops.

**To Reproduce**

Execute the following command,

```
az staticwebapp create \
    -n my-first-static-web-app \
    -g <RESOURCE_GROUP_NAME> \
    -s https://github.com/<YOUR_GITHUB_ACCOUNT_NAME>/my-first-static-web-app \
    -l <LOCATION> \
    -b main \
    --app-artifact-location "build" \
    --token <YOUR_GITHUB_PERSONAL_ACCESS_TOKEN>
```

`az staticwebapp create -l westus2 -n appNameTest1 -g TestPrEnvResourceGroup -s "https://dev.azure.com/myOrganisationName/myProjectName/_git/myRepoName -b "main" --token "generatedTokenValuefwfsdgsgsd"
`

**Error**

Command group 'staticwebapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus Operation returned an invalid status 'Bad Request'
 
https://i.stack.imgur.com/d22hy.png

**Additional Context**

It works well when it is created in portal

**Comment by manekinekko** [comment]
This issue isn't related to the SWA CLI. Please transfer it to https://github.com/Azure/static-web-apps.
