### ISSUE TITLE
CLI exits without message when unable to bind to port 4280

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#212]
**Describe the bug**
If 4280 is in use, the CLI simply exits without an error message. (Note that this behavior is observed while testing #208 and might not affect the current CLI)

```
$ swa start http://localhost:5000
[swa] node "/Users/antchu/source/ms/static-web-apps-cli/dist/msha/server.js" exited with code 0
$
```

**Expected behavior**
Print an error that 4280 is in use before exiting.

**Comment by manekinekko** [comment]
What platform is this? The CLI should print the error message 🤨

![image](https://user-images.githubusercontent.com/1699357/120293581-afe07200-c2c5-11eb-9666-6091a72fd9e1.png)

**Comment by anthonychu** [comment]
Looks like the difference is I'm starting with a dev server instead (`swa start http://localhost:5000`).
