### ISSUE TITLE
Ease the use of self-signed certs

### ISSUE THREAD

**Issue by iMicknl** [Azure/static-web-apps-cli#213]
**Is your feature request related to a problem? Please describe.**
SSL is required when using the media functions, for example to use Azure Communication Services. It is possible to create a local cert, however this is not easy to maintain when multiple contributors work on the same project. You don't want to check a local self-signed cert in your version control.

Dotnet CLI has [a function to generate self-signed certificates](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide) and it would be great if there was similar functionality in static-web-apps-cli. Or at least, if it was possible to plug in a tool to generate (and trust) these certs on the fly.

See https://www.hanselman.com/blog/developing-locally-with-aspnet-core-under-https-ssl-and-selfsigned-certs.

**Describe the solution you'd like**
A better solution, or improved documentation how to handle this issue

**Describe alternatives you've considered**
Just use HTTP and use ngrok or GitHub Codespaces as a SSL reverse proxy during development.

**Comment by manekinekko** [comment]
Landed in #441
