### ISSUE TITLE
Improve handling of staticwebapp.config.json

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#216]
**Is your feature request related to a problem? Please describe.**
Improve experience when using staticwebapp.config.json

**Describe the solution you'd like**
- At startup, print the path of the staticwebapp.config.json that is in use
- Look for staticwebapp**s**.config.json and warn that it is spelled incorrectly
- Validate schema with [schemastore](https://json.schemastore.org/staticwebapp.config.json) and warn if validation failed

**Comment by manekinekko** [comment]
Fixed by https://github.com/Azure/static-web-apps-cli/pull/454
