### ISSUE TITLE
Print notice that the emulator may not match the cloud environment

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#230]
**Is your feature request related to a problem? Please describe.**

There have been some issues filed against the static-web-apps repo because of differences in behavior between the emulator and the Azure environment.

**Describe the solution you'd like**

Print a notice on swa start command:

> This CLI runs an emulator that may not match the cloud environment exactly. Always deploy and test your app in Azure.

We’ve added a similar message to the readme but folks might not see it.

Also make it clear that the CLI is still in preview (but the service is GA).

#229

**Comment by sgollapudi77** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/85578033/123219665-c6f03980-d4ea-11eb-9f36-69c3c9fe6696.png)

@anthonychu will this work?

**Comment by manekinekko** [comment]
@sgollapudi77 can you change that to match this format? And have it printed in yellow?

https://github.com/Azure/static-web-apps-cli/blob/f87dc8b14ba3f1701202f3cb53c44a843dcb377d/src/msha/handlers/function.handler.ts#L56-L59

**Comment by sgollapudi77** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/85578033/123235224-497ff580-d4f9-11eb-89e3-35e5f79bf85e.png)
@manekinekko if this looks good, I'll raise the PR.
