### ISSUE TITLE
`staticwebapp.config.json` in an unexpected folder is loaded

### ISSUE THREAD

**Issue by horihiro** [Azure/static-web-apps-cli#234]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Describe the bug**
`staticwebapp.config.json` in an unexpected folder is loaded.

**To Reproduce**
1. Create the following folder structure.
```
C:\tmp\swa-test
├─dir1
│   └─ staticwebapp.config.json
│
└─dir2
    └─ staticwebapp.config.json
```
2. Go to `dir2`
3. Execute `swa start ..\dir1 --verbose silly`
4. See the log, then it is found that `staticweapp.config.json` in `dir2` (not specified folder) is loaded as following log.

```
[swa] Found configuration file:
[swa]     C:\tmp\swa-test\dir2\staticwebapp.config.json
```

**Expected behavior**
It is expected that `staticwebapp.config.json` in `dir1` is loaded according to the following description in [README.md](https://github.com/Azure/static-web-apps-cli#use-a-configuration-file-staticwebappconfigjson).
```
# ./my-dist is searched for staticwebapp.config.json
swa start ./my-dist
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4566555/121523220-eb4f0f00-ca30-11eb-9511-e87bfa29618e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: n/a
 - Version of SWA CLI: 0.6.0

**Comment by manekinekko** [comment]
Hi @horihiro that's, unfortunately, the expected behavior because SWA was designed to do a lookup from the cwd (./). 
In order to change that behavior, you need to tell the CLI where is your config file is located using the `--swa-config-location` flag.

**Comment by horihiro** [comment]
Thanks @manekinekko !
I forgot that flag you mentioned, sorry for botheing you.
This issue is closed.

**Comment by manekinekko** [comment]
No worries @horihiro. It's alright 😃
