### ISSUE TITLE
Mocking .auth using SWA with Blazor localy not working

### ISSUE THREAD

**Issue by Azuredevmuc** [Azure/static-web-apps-cli#239]
Version: 0.60

**Describe the bug**
Using Blazor with SWA and CLI should bring up possibility to mock .auth localy. This seems not to work.
By following this HowTo: https://anthonychu.ca/post/blazor-auth-azure-static-web-apps/ and by modifying it to the current staticwebapp.config.json, i should be able to use .auth/me or .auth/loging/aad to bring up login mask, right?

This is locally not working - am i missing a route to bring this up in my Blazor app, or is it due to the proxy of SWA CLI?

**To Reproduce**
Follow the sample https://anthonychu.ca/post/blazor-auth-azure-static-web-apps/
Adjust routes.json to be stored in staticwebapp.config.json

Start by using the Blazor command line : swa start http://localhost:5000 --run "dotnet watch run" --api ../Api

**Expected behavior**
by adding /.auth/login/aad to the URL it should bring me to the Login of AAD

**Desktop (please complete the following information):**
Window 10 latest
Chrome

**Additional context**

**Comment by anthonychu** [comment]
This should work. What is the full URL you are navigating to?

**Comment by manekinekko** [comment]
@Azuredevmuc just checking in. Can you confirm you are accessing the default URL: http://localhost:4280?

**Comment by anthonychu** [comment]
I just pushed an updated version of the sample with staticewbapp.config.json. See readme for how to clone and run it locally. https://github.com/anthonychu/blazor-auth-static-web-apps/tree/add-debugging/sample

**Comment by manekinekko** [comment]
@Azuredevmuc I am going to close this issue. Can you try again with the latest version of the CLI and open a new issue if you still have the problem? 

Thank you.
