### ISSUE TITLE
Wrong URI when binding to a dev server using a public hostname

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#251]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
When running the CLI and binding to a dev server using *some* hostnames or a public hostname, the CLI doesn't use the correct domain, nor the port.

**To Reproduce**
1. Go to an Azure Functions app
2. Start the `func` emulator: `func start` (note the used port: 7071)
3. Use a tool such as [ngrok](https://ngrok.com/) to get a domain for localhost: `ngrok http 7071` (note the generated hostname)
2. Go to an SWA project
3. Run the SWA CLI: `swa start ./static --api "http://e7fd8a1ae447.ngrok.io"`
5. See error

**Expected behavior**
The CLI should bind to `http://e7fd8a1ae447.ngrok.io`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1699357/123430609-ad252400-d5c8-11eb-87b9-5bcdf70e82ac.png)

**Comment by connelhooley** [comment]
I'm seeing the same behaviour, just wanted to add that it appears to only impact the API setting . E.g.

```bash
swa start http://app -- api http://api
```

Successfully uses `http://app` for the static front end but it ignores the API setting as described in the inital bug report.

**Comment by sgollapudi77** [comment]
@connelhooley can you verify the behaviour for the static front-end once, I'm also seeing this behaviour for static front-end with custom-url like this?

**Comment by sgollapudi77** [comment]
In my case I can see the custom-url provided is used for serving static content, but I'm getting `read ECONNRESET` when trying to access the link `http://localhost:4280`. Hey @connelhooley Can you confirm once if the same is happening to you or this is happening only to me because of some proxy settings.

![Screenshot (32)](https://user-images.githubusercontent.com/85578033/127557386-0275e2e1-1283-428c-a544-70be95e0b85f.png)

**Comment by connelhooley** [comment]
Hi @sgollapudi77, apologies I don't think I can be much help.

The static content I'm rendering is hosted on `http://localhost:3000` and I haven't had any issues.

I tried to get this running in a docker container, but gave up when I couldn't configure the API endpoint to be something other than localhost so I haven't actually used anything other than localhost.
