### ISSUE TITLE
CRA with 5 functions won't load 0.0.0.0:4280

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/static-web-apps-cli#252]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x ] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
When I have multiple azure functions and a CRA front end it doesnt seem to load when running locally
* The CRA and azure functions work in isolation

**To Reproduce**
1. Create 5 azure functions ( I happen to have 5)
2. Introduce a CRA app
3. Run swa start 
* The page doesnt load 0.0.0.0:4280 
However it runs the APIs on 7071 and the frontend on 3000

**Expected behavior**
I should be able to see the front end and validate my static web app

**Desktop (please complete the following information):**
- Github codespaces

**Additional context**

**Comment by alkwa-msft** [comment]
Is there any way to debug the SWA emulator to understand what might be crashing so I can proceed to continue development?

 I can deploy to Azure and it runs but the inner loop is extremely long if I need to deploy to Azure to validate my changes

**Comment by alkwa-msft** [comment]
It turns out its a mixture of my CRA dev server not starting up in time and the routes were not properly configured on the react-router. 

I am wondering if there is still a way to increase the time to wait for the CRA dev server in the ASW CLI?

**Comment by manekinekko** [comment]
Thank you @alkwa-msft for reporting this. I think it's a good idea to add a flag to let you configure the await time.
