### ISSUE TITLE
Allow configuring the await timeout before connecting to a dev server

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#253]
**Is your feature request related to a problem? Please describe.**
When running the CLI against a dev server, we currently await 30 seconds (by default) for the dev server to start before connect to it (see https://github.com/Azure/static-web-apps-cli/issues/252)

So users have reported that some dev servers might take longer. We need a new flag to configure that timeout.

**Describe the solution you'd like**
Introduce a new flag `--wait-on-timeout` that maps to an env variable `SWA_CLI_WAIT_ON_TIMEOUT`, and update all references to `validateDevServerConfig()` defined in: https://github.com/Azure/static-web-apps-cli/blob/95b6e5641707abaef42b2db7fb21885e8783f5bc/src/core/utils/net.ts#L48

cc @anthonychu

**Comment by alkwa-msft** [comment]
ltgm I am thinking wait-on-timeout might be too ambiguous? Since its specifically for waiting on a frontend devserver 

--devserver-init-timeout?

**Comment by manekinekko** [comment]
This would be used for both frontend and API (when using dev server).

I agree on the naming, but let's make it shorter: `--devserver-timeout`.
