### ISSUE TITLE
Discussion - Startup commands

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#26]
```bash
# serve static assets from disk at ./app_artifacts, no api
swa start app_artifacts

# proxy to (ng/react/vue etc) dev server that is already running, no api
swa start http://localhost:4200

# run with api project in ./api
swa start app_artifacts --api api

# run with api project in ./api, but serve api from http://localhost:<port>/functions
swa start app_artifacts --api api --api-prefix functions

# build app with default command (npm run build?) from ./app
# then serve as static assets from build output (./app_artifacts)
swa start app_artifacts --build-app app

# build app with specific command
swa start Client/bin/Debug/net5.0/publish/wwwroot --build-app Client --build-app-command "dotnet publish"

# run with settings in swa.config
swa start 
```

By default, it can try to search for `routes.json` or the new config file and use it.
1. Use the file in the app artifacts folder (if supplied)
1. Search recursively from current folder and use the first config file that it finds.

Optionally, allow specifying location of the routes/config file:

```bash
swa start http://localhost:5000 --config Client/wwwroot/routes.json
```

How VS Code might start the emulator:

```bash
swa start http://localhost:4200 --api api
```

**Comment by aaronpowell** [comment]
I think this somewhat overlaps with #15, where it's hard to make it work unless you already have a workflow file.

I don't know if sub commands really provide much value though, what else would there be other than `start`? Is this where #21 comes into play, so you'd have a `init` command?

**Comment by anthonychu** [comment]
Yep the plan is this will change from an emulator to a CLI. Deploy/publish will eventually be part of it too.

**Comment by aaronpowell** [comment]
Oh right, so have it move more towards things like `func`?

Can I request an ASCII logo 😜

**Comment by anthonychu** [comment]
I have reached my limit of 1 ASCII art scandal this year.
