### ISSUE TITLE
Using a function as a fallback route doesn't work

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#261]
**Describe the bug**
Functions should be able to be used as navigation fallback like configured [here](https://github.com/anthonychu/test-swa-ssr/blob/758d54b98c26c383a1cb5535c51cd4b03309f877/public/staticwebapp.config.json#L12-L14) but it doesn't work.

**To Reproduce**
1. git clone https://github.com/anthonychu/test-swa-ssr.git
2. cd test-swa-ssr
3. swa start public --api api
4. Navigate to http://localhost:4280/foo returns the 404 page

**Expected behavior**
Navigating to http://localhost:4280/foo should return the function response. This works when deployed to Azure.

**Comment by sgollapudi77** [comment]
Fixed with #314
