### ISSUE TITLE
secure route + responseOverride=401 + redirect=/login.html does not work.

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#266]
**Describe the bug**
Protecting a route using the following configuration doesn't seem to work.
```
{
    "responseOverrides": {
        "401": {
            "redirect": "/login.html"
        }
    },
    "routes": [
        {
            "route": "/",
            "allowedRoles": [
                "authenticated"
            ]
        }
    ]
}
```

1. Create and `cd` to new folder `swa-demo`
1. Create an `index.html` file
1. Create a `staticwebapp.config.json` file with 
```
{
    "responseOverrides": {
        "401": {
            "redirect": "/login.html"
        }
    },
    "routes": [
        {
            "route": "/",
            "allowedRoles": [
                "authenticated"
            ]
        }
    ]
}
```
1. Type in command `swa start`
1. Access URL: `http://localhost:4280/`
1. Make sure you **are not authenticated**.
1. See error: browser does not redirect to `http://localhost:4280/login.html`

**Expected behavior**
Following the steps above, non-authenticated users should be redirected to `http://localhost:4280/login.html`

**Comment by sgollapudi77** [comment]
Merged a PR relating to this issue. Closing this.
