### ISSUE TITLE
Release with #255

### ISSUE THREAD

**Issue by richarddavenport** [Azure/static-web-apps-cli#270]
Is there a release coming soon now that #255 has been released? 

That is a feature we've been waiting for. We have a slow angular build and the `--devserver-timeout` flag helps us out tremendously!

I can run the cli locally with `npm link` but it's not feasible for everyone on the team to be forced to do that.

Thanks to everyone working on a great solution!

**Comment by anthonychu** [comment]
0.7.1 is released! 🎉
