### ISSUE TITLE
Question about how to make proxy work?

### ISSUE THREAD

**Issue by diberry** [Azure/static-web-apps-cli#282]
I have an app structure like:

```
\ (root)
-- \ app (react client)
-- \ api (azure function api)
```

The root has the following package.json with the two different apps having separate scripts to start the dev servers:

```json
{
  "name": "swa-1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start-api": "cd api & func host start",
    "start-app": "cd app & npm start",
    "start-dev": "concurrently \"npm:start-api\" \"npm:start-app\" ",
    "start-swa": "swa start http://localhost:3000 --api http://localhost:7071",
    "start": " npm run start-dev && npm run swa-up",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/diberry/temp.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/diberry/temp/issues"
  },
  "homepage": "https://github.com/diberry/temp#readme",
  "dependencies": {
    "@azure/static-web-apps-cli": "^0.6.1"
  },
  "devDependencies": {
    "azure-functions-core-tools": "^3.0.3568",
    "concurrently": "^6.2.1"
  }
}
```

The react app is very minimal just to figure out how to use the swa cli. The only change is to the `App.js` to call the API. 

**My expectation is that the API route `/api/HttpHello?${name}` will be proxied correctly to the locally running backend function app but it isn't so far so I must be missing something in my set up . What am I doing wrong?** Also, if I add the proxy property setting to the React package.json everything works so I'm missing why I would use the SWA CLI. 

```javascript
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {

  const [name, setName] = React.useState('');
  const [message, setMessage] = React.useState('');


  const getDataFromApi = async(e: any)=>{
    e.preventDefault();
    const data = await fetch(`/api/HttpHello?${name}`);
    const json = await data.json();

    if (json.message){
      setMessage(json.message);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Static Web App: React App with Azure Function API
        </p>
        <form id="form1" className="App-form" onSubmit={e => getDataFromApi(e)}>
          <div>
            <input 
              type="text" 
              id="name" 
              className="App-input" 
              placeholder="Name" 
              value={name} 
              onChange={e=>setName(e.target.value)} />
            <button type="submit" className="App-button">Submit</button>
          </div>
        </form>
        <div><h5>Message: {message} </h5></div>
      </header>
    </div>
  );
}

export default App;
```

The function app is nothing special - the template HTTP trigger API.

**Comment by diberry** [comment]
Not sure where I went wrong but it is working now. 

1. Run `npm run start-dev` in a split-window in VS Code.
2. Run 'npm run start-swa` in the second split-window. 
3. Browser http at `http://localhost:4280`.

**Comment by manekinekko** [comment]
Hey @diberry yeah, that's currently the expected usage:
1. run the api
1. run the app
1. run `swa http://app-dev-server --api http://api-dev-server`

Alternatively, you can also use the `--run` flag to run an arbitrary shell commands, such as starting the app or api dev servers automatically. For example:

`swa start http://localhost:3000 --api http://localhost:7071 --run "npm run start-dev"`

Also, make sure to use the latest version of the SWA CLI, in order to benefit from the `--devserver-timeout` flag, which allows you to set a timeout (in ms) to wait for the dev servers to start:

`swa start http://localhost:3000 --api http://localhost:7071 --run "npm run start-dev" --devserver-timeout 60000`
