### ISSUE TITLE
rewrites in development have incorrect path

### ISSUE THREAD

**Issue by mcansh** [Azure/static-web-apps-cli#286]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
Hey! I'm working on bringing Azure support to [Remix](https://remix.run)! I have a rewrite which rewrites all paths to a function and when I start up my local server `swa start ./public --run "remix dev" --api .` and console.log the current path, I'd expect to see it be `/`, but I'm getting that of the function `/api/azure` - here's my app's repo https://github.com/mcansh/remix-on-azure and here it is working when deployed https://brave-wave-0feb78710.azurestaticapps.net

**To Reproduce**
1. Create a function and rewrite all paths to point to that function
2. Type in command `swa start ./public --run "remix dev" --api .`
3. Go to http://localhost:4280
5. See error

**Expected behavior**

our request url will be "/"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome, safari, firefox
 - Version [e.g. 22] 95.0.4623.0, 15.0, 93.0a1

**Additional context**

**Comment by danielgary** [comment]
I investigated this issue a few months back.  Remix needs the original URL to be preserved even after the fallback.  In production, this works and we can access the original URL using the ```x-ms-original-url``` header, but that header is not set when using the cli.
