### ISSUE TITLE
File without extension return 404

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#292]
**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
When fetching a file that doesn't have an extension (eg. `foo`), the CLI returns a `404`.

**To Reproduce**
1. Create an HTML file with the following content:
```
<script>
  window.onload = async function () {
    foo.innerText = (await fetch("/foo")).status;
  };
</script>
<p>foo: <code id="foo"></code></p>
```
3. Create an empty file `foo` (without an extension!)
3. Run `swa start ./ --verbose silly`
5. See error: file `foo` isn't found.
6. Accessing `http://localhost:4280/foo` also returns a `404`

**Expected behavior**
The file `foo` should be fetched and accessed successfully.

**Additional context**

The issue seems to come from this function:

https://github.com/Azure/static-web-apps-cli/blob/bf4fbcb0e6af12695b8f24b886098be8df9e7c9c/src/msha/routes-engine/rules/routes.ts#L16-L35

Here are the logs from the `swa` command.

```
[swa] --------------------------------------------------------
[swa] ------------------- processing route -------------------
[swa] --------------------------------------------------------
[swa] processing /foo
[swa] checking for matching route
[swa] checking auth request
[swa]  - not an auth request
[swa] checking function request
[swa]  - not a function request
[swa] checking HTTP method: GET
[swa]  - method is valid (allow-list: GET,HEAD,OPTIONS)
[swa] checking for query params
[swa] checking rewrite auth login request
[swa] checking rewrite auth logout request
[swa] checking authorizations for route
[swa]  - no matching rule
[swa]  - access authorized
[swa] using userConfig
[swa]  - userConfig: <undefined>
[swa] checking storage content
[swa] finding file for request
[swa]  - requestPath: /foo/index.html
[swa]  - filePath: /Users/wassimchegham/swa-cli-issue-test/foo/index.html
[swa]  - exists: false
[swa]  - filePathFromRequest: null
[swa]  - shouldDisplayNotFoundPage: true
[swa] GET http://localhost:4280/404.html - 404
[swa]  - url: /404.html
[swa]  - target: /Users/wassimchegham/swa-cli-issue-test/
[swa] customUrl: false
[swa] is4xx: true
[swa] checking if file exists in user's output location
[swa]  - file: /Users/wassimchegham/swa-cli-issue-test/404.html
[swa]  - exists: false
[swa] checking if file exists in CLI public dir
[swa]  - file: /Users/wassimchegham/oss/@azure/static-web-apps-cli/dist/public/404.html
[swa]  - exists: true
[swa] serving static content
[swa]  - file: /Users/wassimchegham/oss/@azure/static-web-apps-cli/dist/public/404.html
[swa]  - url: /404.html
[swa]  - code: 404
```

**Comment by santoshyadavdev** [comment]
I can take it 😊

**Comment by sgollapudi77** [comment]
https://github.com/Azure/static-web-apps-cli/pull/293 - Fixed with this
