### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#32]
**Is your feature request related to a problem? Please describe.**
Currently, running `swa` inside a monorepo project such as [shopathome](https://github.com/johnpapa/shopathome) (by @johnpapa) , will give unexpected behaviors.

**Describe the solution you'd like**
The emulator needs to support:
- monorepo projects
- multiple workflow GitHub files (one per sub-project)

**Comment by itpropro** [comment]
I would like to add to support multiple workflow files for the same project. We have multiple SWA projects, where we have 2-3 workflow files to represent multiple stages. These could be combined into a single one, but if you stay with what Azure initializes in your repo, you will have one workflow file per connected SWA in Azure (e.g. Dev, Test, Prod).

**Comment by manekinekko** [comment]
Thank you @itpropro for the feedback.
