### ISSUE TITLE
Proxy can't connect to Functions CLI v4

### ISSUE THREAD

**Issue by uxsoft** [Azure/static-web-apps-cli#335]
Azure Static Web Apps CLI can't connect to Azure Functions V4 CLI. The same issue with webpack or parcel proxy.

```
[swa] × Waiting for http://localhost:7071 to be ready
[swa] Could not connect to "http://localhost:7071". Is the server up and running?
```

But when I go to localhost:7071 I can see the "Your Functions 4.0 app is up and running" page working just find and I can send requests using postman or web browser and they work just fine.

```
> func --version
4.0.3780
```
I'm running Windows 11 22000.282. Tried turning the firewall off but didn't help.

Repro: https://github.com/uxsoft/swa-bolero-template/

**Comment by uxsoft** [comment]
switching from node 17 to node resolved the  issue for me as well!

**Comment by piotr-lasota** [comment]
Similiar here. Failed on Node 16 and 17 (same scenarios). Switching to node@14 on mac fixed the issue but it feels like a workaround with 16 being the current LTS

**Comment by zachmatson** [comment]
Digging around a bit, it seems like this is related to https://github.com/nodejs/node/issues/40702

**Comment by Azuredevmuc** [comment]
NodeJS Version 16 LTS is working fine on Windows 10. Remember to reboot after uninstall / install.
This issue can be closed, since it is not a related Issue to static-web-apps-cli? @anthonychu

**Comment by uxsoft** [comment]
The issue for me was on Node 17, not Node 16. It works for me on Node 16 too but that doesn't solve the issue.

**Comment by manekinekko** [comment]
@uxsoft  The underlying Azure Function Core Tools tool does not support Node.js 17. We've added a check (https://github.com/Azure/static-web-apps-cli/commit/d1b83d5bc3d13e991626f4366d54f49fb8ea5334) to prevent this issue.

For more information about supported Azure Function Core Tools versions: https://aka.ms/functions-node-versions.

I am closing this thread. Please open a new issue if needed.

**Comment by zachmatson** [comment]
This is not exclusively an issue with functions core tools. The same issue appears when setting the APIs to be served from a local server on Node 17 without running functions core tools at all.

**Comment by manekinekko** [comment]
@zachmatson the SWA CLI uses Azure Functions Core Tools to run the API on your behalf.

**Comment by pdaplyn** [comment]
I get the same issues with Node 18, so stick with 16 for now for an easy life.
