### ISSUE TITLE
x-ms-original-url should reflect the value before rewrite

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#337]
Reported by @smakinson https://github.com/Azure/static-web-apps/issues/580#issuecomment-959978998

**Comment by smakinson** [comment]
Thanks! Definitely something we need to easily test a custom sr like setup.

**Comment by danielgary** [comment]
I believe this was fixed in #314 and should already be released?

**Comment by manekinekko** [comment]
I confirm this has been fixed in #314

**Comment by manekinekko** [comment]
Closing this issue as the fix has been merged into main.
