### ISSUE TITLE
SWA with React + Vite development server returns HTTP 404 for requests with parameters

### ISSUE THREAD

**Issue by tonakai** [Azure/static-web-apps-cli#346]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

```
> swa --version
0.8.1
```
**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
I've started application `swa start http://localhost:3000 --run "npm run dev"`.

I have React Typescript Vite application that fails to load some queries specially the ones with a http parameter for example:

```
Request URL: http://localhost:4280/node_modules/.vite/react.js?v=4fc4987f
Request URL: http://localhost:4280/node_modules/.vite/react-dom.js?v=4fc4987f
Request URL: http://localhost:4280/node_modules/.vite/react_jsx-dev-runtime.js?v=4fc4987f
```

they all returned HTTP 404 when I visited the localhost:4280

when I simply go to the development server it seems be working without any problem albeit their content are a bit different so that parameter is useful somehow to the vite development server.

when I remove the `?v=xxx` part from those urls, it passes correctly.

**To Reproduce**
 `npm init vite@latest swa-vite-react-ts-test --template react-ts`
`cd swa-vite-react-ts-test`
`npm install`
`npm install -g @azure/static-web-apps-cli`
`swa start http://localhost:3000 --run "npm run dev"`
`go to localhost:4280 and take a look at network/console`

**Expected behavior**
I'd expect it to simple run and load the app

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge/Chrome
 - Version: both 95

**Comment by manekinekko** [comment]
Thank you for opening this issue. It look like this is related to #339

**Comment by mellson** [comment]
I got this working by downgrading to 0.8.0 as [suggested here](https://github.com/Azure/static-web-apps-cli/issues/339#issuecomment-979658966).

Look forward to a fix in the coming versions.

**Comment by mellson** [comment]
Yay, the new 0.8.2 fixed this for me. Thanks 🙏🏻
