### ISSUE TITLE
Install azure-functions-core-tools when the user is trying to run swa start with the --api-location flag

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps-cli#353]
**Is your feature request related to a problem? Please describe.**
Currently users have to install azure-functions-core-tools if they need to run the API.  

**Describe the solution you'd like**
When users are trying to run swa start --api-location, detect if they don't have azure-functions-core-tools installed and ask if they want to install it. This would lead to a better user experience and faster path to success.

**Describe alternatives you've considered**
Install the tools separately

**Additional context**
Installing the core tools separately requires context switching and many times users are not successful because they don't land on the right version or the simplest install command. First time users might not know why they need it and why so they might skip this step. 

recommended install using npm:

npm i -g azure-functions-core-tools@3 --unsafe-perm true

**Comment by anthonychu** [comment]
Probably should install v4. Ideally it’ll select based on language and version to match the service but maybe just install v4 by default if func is not available, and user can downgrade if needed.

**Comment by sinedied** [comment]
Is NPM still a valid/recommended way of installing core tools? I remember having issues with the core tools install silently failing (ie core tools not being available despite the package being installed) depending of the OS used.

The NPM package's readme itself states to use `brew` on MacOS or `dpkg` on Linux.

**Comment by anthonychu** [comment]
Not sure if it’s worth investigating but theoretically SWA cli can download the func binary and run it, and it doesn’t need to depend on a separately installed version. This is more work, but there are advantages such as using the right version of core tools for the language in the project (.NET 6 requires v4, Node currently uses v3) and always keep the core tools up to date. Example of how to download the binary and start the right one: https://github.com/anthonychu/funcvm

**Comment by sinedied** [comment]
Just giving a heads up as I'm currently working on direct download of the func tools correct version based on @anthonychu's suggestions 🙂

**Comment by anthonychu** [comment]
Nice. Just a heads up that we might want to reach out to functions team to ensure we are looped in if there are any planned changes to how this works. I’m not aware of any plans to change the feed and download methods but should confirm.

**Comment by sinedied** [comment]
I've sent the PR for this 🙂 : https://github.com/Azure/static-web-apps-cli/pull/391

I have two questions now:
1. Should we include a CLI flag to clean-up downloaded core tools?
2. Should we check for newer Core Tools version (than installed locally) and automatically update it?

**Comment by sinedied** [comment]
Also @anthonychu do you know someone we could reach out to regarding the feed question?

**Comment by manekinekko** [comment]
> I've sent the PR for this 🙂 : #391
> 
> I have two questions now:
> 
> 1. Should we include a CLI flag to clean-up downloaded core tools?
> 2. Should we check for newer Core Tools version (than installed locally) and automatically update it?

Is this really needed? If the local `func` is only meant to be used by SWA CLI, I guess we are safe to override old versions with a new version - assuming that we validate any new major `func` binary ahead of time.
