### ISSUE TITLE
Files are not found if contain percent encoded symbols

### ISSUE THREAD

**Issue by DeividasBakanas** [Azure/static-web-apps-cli#370]
CLI Version: 0.8.2

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
Files containing percent-encoded symbols are not found. When opening a file with the name `with space.html`, the browser will percent-encode space symbol to `%20` and request the file as `with%20space.html`. This will result in a 404 HTTP status for the request.

**To Reproduce**

1. Go to https://stackblitz.com/edit/node-fxhtv9?devtoolsheight=33&file=src/index.html
2. In the terminal type in the command 'npm start'
3. Open https://node-fxhtv9--4280.local.webcontainer.io/index.html in a separate browser window.
3. Click on a link 'With space'
4. See the page responded with an error.

**Expected behavior**
When requesting files with percent-encoded symbols, server should percent-decode requested URL and only then produce the response.

**Desktop:**
- OS: Windows 10 Enterprise 18363
- NodeJS: tested with v14.16.0, v16.13.1
- Browser: Google Chrome 97.0.4692.71, Firefox 96.0, Edge 97.0.1072.55

**Comment by manekinekko** [comment]
Thank you @DeividasBakanas for reporting this issue
