### ISSUE TITLE
[Regression] Query string on static content doesn't work anymore

### ISSUE THREAD

**Issue by jeremyVignelles** [Azure/static-web-apps-cli#375]
**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
Same use case as #229 : I am trying to use a static file with a query string, like `/control.html?param=someParam`.

SWA tries to serve a file with that name, but fails to find it because of the query string, which results in a 404.

**To Reproduce**
The tests written here should be enough to reproduce : https://github.com/Azure/static-web-apps-cli/pull/236/files#diff-ba4c499cc1f8e723c549aa4cef659acd150c990f06dc54434ad654e527a525f4

However if I run `npm run cy:run`, 61 tests are failing, so I can't really test.

**Expected behavior**
The requested file should be served.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: curl is enough to reproduce
 - Version 

**Additional context**
Looking at git blame :
#229 was fixed by @manekinekko in #236 .
That changed was reverted by @sgollapudi77 in #336 , and further modified by @garand in #338.

Now, we have this code in place:

```
  let matchingRewriteRoutePath = matchingRewriteRoute ? matchingRewriteRoute : undefined; // < matchingRewriteRoute is string | undefined, so why the ternary here ?

  if (doesMatchingRewriteRouteHaveQueryStringParameters) { // < If we have query string
    matchingRewriteRoutePath = sanitizedUrl.pathname + sanitizedUrl.search;// <Take the path and add again the query string
    logger.silly(` - query: ${chalk.yellow(matchingRewriteRouteQueryString)}`);
  }
  return { matchingRewriteRoutePath, sanitizedUrl, matchingRewriteRoute }; // < Return both matchingRewriteRoutePath and matchingRewriteRoute
```

The point of adding that `if (doesMatchingRewriteRouteHaveQueryStringParameters)` in the first place was to remove the query string from problematic calls. In my tests, `matchingRewriteRoutePath` now yields the same values as `matchingRewriteRoute` (`/control.html?param=someParam`).

Since both variables are returned, I think that you may use `matchingRewriteRoute` higher up in the call if you really need the queryString, instead of relying on `matchingRewriteRoutePath`, which, as its name suggest, should return the path, without the query string

**Comment by abhimantiwari** [comment]
@manekinekko Do we have any tentative timeline for release of this fix?

**Comment by kaylumah** [comment]
I am running into the same issue where assets like css files are loaded with cache breaker ?v=someuniqueid this fails on the cli

**Comment by manekinekko** [comment]
I am planning to work on this issue, this week. Will keep you posted.
