### ISSUE TITLE
Enable building api code upon start

### ISSUE THREAD

**Issue by janirapo** [Azure/static-web-apps-cli#380]
I have setup my api using TypeScript and I am unable to startup both the frontend and the api at the same time using the `swa start` command, because the TypeScript code needs to be built before you can run it as JavaScript.

Instead of running `func start` in the api folder you should provide a way to run e.g. `npm start` within that folder, so that the developer can setup prestart tasks that build the code before trying to run it. My suggestion would be to add parameter `--run-api`, so that you could use `--run-api="npm start"`, which would run the command in the api folder.

An alternative way could be to provide a way to run a pre-start task, so that you can build the api by separate parameter at beforehand. E.g. `--build-api="npm run build"`, which would run the command within the api folder.

**Comment by JeffreyCA** [comment]
As a workaround I modified the `build` script of the root `package.json` so it builds both the front-end and API when you run `npm run build` from the root dir.

```json
"scripts": {
    ...
    "build": "npm run build --prefix api && react-scripts build",
    ...
},
```
