### ISSUE TITLE
Add claims to local emulator login screen and /.auth/me local endpoint

### ISSUE THREAD

**Issue by hags1975** [Azure/static-web-apps-cli#386]
Can't provide claims in local emulator.

Provide an array input of claims similar to what you see in a live static web app site in the local login form.

![image](https://user-images.githubusercontent.com/22360470/152893316-0c456118-c0d4-445f-9f91-e10ab0742f35.png)

Link to documenation:
https://docs.microsoft.com/en-us/azure/static-web-apps/local-development

**Comment by manekinekko** [comment]
Related PR #381

**Comment by scottkuhl** [comment]
Before I open a bug, is this the same issue:

If I add the role "tester" or "admin" to the mock auth UI shown above and then try to access if that principal has that role in an Azure function it is never found.  No roles are being sent across.

I tried this method from the docs:
`req.Headers.TryGetValue("x-ms-client-principal", out var header)`
and that header is not found.

I tried this method:

```
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "secured/HelloYou")] HttpRequest req,
            ILogger log,
            ClaimsPrincipal principal)
        {
            if (principal == null || !principal.Identity.IsAuthenticated || !principal.IsInRole("admin"))
```

also not found.

**Comment by egeyer** [comment]
@scottkuhl I somehow missed your reply to this issue when I was searching.  I have the exact same issue that you did and opened up a bug/question for it here: #390   I assume if it's a duplicate, it will be cleaned up, but I've been stumped on getting this to work.
