### ISSUE TITLE
swa start says --api option unknown, yet requires it

### ISSUE THREAD

**Issue by williamheelis** [Azure/static-web-apps-cli#388]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
--api option is an unknown option, yet required

**To Reproduce**
1. Go to '[...](https://www.youtube.com/watch?v=MF-nvoTUouk&t=2510)'
2. Type in command 'swa start www' 
3. watch error ask for 'Please use the --api option'
4. Type in command 'swa start www --api .' 
5. See error 'error: unknown option '--api''

**Expected behavior**
I want to add --api option but it is not recognised, but the warning insists I add is (see code block). I am following AnthonyChu's youtube https://www.youtube.com/watch?v=MF-nvoTUouk&t=2510 and the command is legit (I believe)

**Screenshots**
```
~/Projects/AnthonyChuDemo(master|…) % swa start www      
[swa] 
[swa] Serving static content:
[swa]     /Users/c0b0dpd/Projects/AnthonyChuDemo/www
[swa] 
[swa] 
[swa] This CLI is currently in preview and runs an emulator that may not match the 
[swa] cloud environment exactly. Always deploy and test your app in Azure.
[swa] 
[swa] 
[swa] Azure Static Web Apps emulator started at http://localhost:4280. Press CTRL+C to exit.
[swa] 
[swa] 
[swa] ***************************************************************************
[swa] ** Functions request detected but no endpoint configuration was found.   **
[swa] ** Please use the --api option to configure a function endpoint.         **
[swa] ***************************************************************************
[swa] POST http://localhost:7071/api/negotiate?negotiateVersion=1 (proxy)
[swa]  ↳ POST http://localhost:7071/api/negotiate?negotiateVersion=1 - 502 (Bad Gateway)
^C[swa] node "/Users/c0b0dpd/.nvm/versions/node/v16.13.0/lib/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code 0
~/Projects/AnthonyChuDemo(master|…) % swa start www --api .                                  
error: unknown option '--api'
```

**Desktop (please complete the following information):**
 - OS: macOS[e.g. iOS]
 - Browser firefox[e.g. chrome, safari]
 - Version 0.8.2 [e.g. 22]

**Additional context**

**Comment by anthonychu** [comment]
It’s been changed to `--api-location` but that error message is outdated. We’ll get it updated. Sorry about that! https://github.com/Azure/static-web-apps-cli/blob/0ea71464a703003c6e6b239e59a124b1cb328211/src/msha/handlers/function.handler.ts#L58

**Comment by williamheelis** [comment]
thanks, also it isn't possible to install older versions via `npm install -g @Azure/static-web-apps-cli@v0.8.1` can you advise the correct way to do previous version installs with this package? and possibly add it to the readme?

**Comment by williamheelis** [comment]
also, may I recommend that the error message `error: unknown option '--api'` be changed to `error: in version 0.8.x and above option '--api' is changed to --api-location`

**Comment by williamheelis** [comment]
sorry to be a pain, but @anthonychu I now get this error
<img width="987" alt="Screenshot 2022-02-22 at 09 18 26" src="https://user-images.githubusercontent.com/82875267/155101231-9467d140-495b-4d5e-a5fa-ff209973967c.png">

`Could not connect to "http://localhost:7071". Is the server up and running?` 

then after some delay 

```
node "/Users/c0b0dpd/.nvm/versions/node/v16.13.0/lib/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code 0
[api] Value cannot be null. (Parameter 'provider')
[api] cd "/Users/c0b0dpd/Projects/AnthonyChuDemo" && func start --cors "*" --port 7071  exited with code 0
```

I know that `swa` runs both the `4280` and the `7071` ports but I thought the 4280 port was my gateway and the 7071 was a internal route used by swa. so why does 

`swa start www` run `http://localhost:4280`

yet 

`swa start www --api-location .` run `http://localhost:7071`?

**Comment by sgollapudi77** [comment]
Hey @williamheelis , please check this issue #335 I think you're encountering a similar error.
