### ISSUE TITLE
Emulator won't start

### ISSUE THREAD

**Issue by dougclutter** [Azure/static-web-apps-cli#392]
**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`...well, I am trying to 

> Make sure you are accessing the URL printed in the console when running!
There is no URL printed in the console.

**Describe the bug**
The emulator never launches.  The console reports that the **server.js exited with code 0**.
I have tried a bunch of things:
- Building the client and/or the api from the swa command line
- Uninstalled/re-installed both swa and func
- Disabled the firewalls
- Ran the console as an Admin
- Cleared all content from staticwebapp.config.json to confirm it wasn't due to a JSON formatting issue
- Tried using port 8080 instead of port 4280

**To Reproduce**
1. Launched both the API project and the Client project (Blazor WASM) from Visual Studio 2022.  
2. Confirmed that both the Client and API were responding on the ports I used below.  
3. `cd client` (this is the directory with my staticwebapp.config.json file)
4. `swa start http://localhost:5000 --api-location http://localhost:7071 --print-config`
[swa]
[swa] Options:
[swa]  - port: 4280
[swa]  - host: localhost
[swa]  - apiPort: 7071
[swa]  - apiPrefix: api
[swa]  - ssl: false
[swa]  - appLocation: .\
[swa]  - outputLocation: .\
[swa]  - swaConfigLocation: .\
[swa]  - sslCert: <undefined>
[swa]  - sslKey: <undefined>
[swa]  - appBuildCommand: npm run build --if-present
[swa]  - apiBuildCommand: npm run build --if-present
[swa]  - swaConfigFilename: staticwebapp.config.json
[swa]  - swaConfigFilenameLegacy: routes.json
[swa]  - run: <undefined>
[swa]  - verbose: log
[swa]  - customUrlScheme: swa://
[swa] - overridableErrorCode:
[swa]   - 0: 400
[swa]   - 1: 401
[swa]   - 2: 403
[swa]   - 3: 404
[swa]  - devserverTimeout: 30000
[swa]  - build: false
[swa]  - apiLocation: http://localhost:7071
[swa] node "C:\Users\dougc\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\server.js" exited with code 0

5. SWA exits without anything further
6. http://localhost:4280 will not respond...I had to try  

**Expected behavior**
The emulator should launch.  http://localhost:4280 should respond with content.

**Screenshots**
Shown in-line above

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows 11 Pro]
 - Browser [edge]
 - Version [98]
 
**Additional context**
`node --version`
v16.14.0

`systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000

`npm list -g`
C:\Users\dougc\AppData\Roaming\npm
+-- @azure/static-web-apps-cli@0.8.2
+-- azure-functions-core-tools@3.0.3904
`-- npm@8.5.2

**Comment by manekinekko** [comment]
Would you mind sharing the logs as well? You can enable logs using `--verbose=silly` like so:
```
swa start http://localhost:5000 --api-location http://localhost:7071 --verbose=silly
```

**Comment by dougclutter** [comment]
Run from the Client folder:
**swa start http://localhost:5000 --api-location http://localhost:7071 --verbose=silly**
[swa] - ssl:
[swa]   - 0: false
[swa]   - 1: <undefined>
[swa]   - 2: <undefined>
[swa] - env:
[swa]   - SWA_CLI_DEBUG: silly
[swa]   - SWA_CLI_API_PORT: 7071
[swa]   - SWA_CLI_APP_LOCATION: C:\Dev\myDocDrawer\src\myDocDrawer\Client\
[swa]   - SWA_CLI_OUTPUT_LOCATION: http://localhost:5000
[swa]   - SWA_CLI_API_LOCATION: http://localhost:7071
[swa]   - SWA_CLI_ROUTES_LOCATION: .\
[swa]   - SWA_CLI_HOST: localhost
[swa]   - SWA_CLI_PORT: 4280
[swa]   - SWA_WORKFLOW_FILES: <undefined>
[swa]   - SWA_CLI_APP_SSL: false
[swa]   - SWA_CLI_APP_SSL_CERT: <undefined>
[swa]   - SWA_CLI_APP_SSL_KEY: <undefined>
[swa]   - SWA_CLI_STARTUP_COMMAND: <undefined>
[swa]   - SWA_CLI_VERSION: 0.8.2
[swa]   - SWA_CLI_DEVSERVER_TIMEOUT: 30000
[swa] - commands:
[swa]   - swa: node "C:\Users\dougc\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\server.js"
[swa]   - api: <undefined>
[swa]   - run: <undefined>
[swa] killing SWA CLI
[swa] node "C:\Users\dougc\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\server.js" exited with code 0

I just tried running it from the Api folder, and it appears to work!!
I'll let you know what else I find. :)

Thanks so much for publishing this tool!  I can't wait to use it more!

**Comment by manekinekko** [comment]
That's interesting! yes, please keep me posted as I cannot reproduce this issue locally.
