### ISSUE TITLE
Update node.js and npm version

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#394]
Node.js 14 is going to be deprecated. We need to move to the next LTS version and set those versions in package.json.

**Comment by Devansu-Yadav** [comment]
@manekinekko Is this issue open to take up? If yes, I would like to contribute to this and make my first contribution to the project 🙂

I'd need a little bit of help getting started, hope that's fine 😅

Just wanted to ask where else do I need to update the versions for `nodejs` and `npm` apart from the `package.json` file?

**Comment by manekinekko** [comment]
Hey @Devansu-Yadav thank you for wanting to help. Yes, this issue is still open.

Here are some of the places where we reference `node` and `npm` versions we depend on:
- https://github.com/Azure/static-web-apps-cli/blob/main/.nvmrc
- https://github.com/Azure/static-web-apps-cli/blob/main/package.json (engines)
- https://github.com/Azure/static-web-apps-cli/blob/main/.devcontainer/Dockerfile
- https://github.com/Azure/static-web-apps-cli/blob/main/.devcontainer/devcontainer.json
- https://github.com/Azure/static-web-apps-cli/blob/main/.github/workflows/azuresdkdrop.yml (packageAndRelease job)
- https://github.com/Azure/static-web-apps-cli/blob/main/.github/workflows/node.yml (package job)

Thank you 🙏
