### ISSUE TITLE
Fix e2e tests setup in GitHub Actions

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#400]
We have disabled our current e2e test (see https://github.com/Azure/static-web-apps-cli/pull/398/commits/1a42f73cc6e0cfe0888d38308ac981290e89bbea) due to some issues with Cypress.

We'd like to enable e2e tests again once we manage to investigate the root cause.

**Comment by Reshmi-Sriram** [comment]
Related issue: [#352 ](https://github.com/Azure/static-web-apps-cli/issues/352)
