### ISSUE TITLE
swa start context should use swa-cli.config.json root folder

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#409]
**Describe the bug**
When starting the SWA CLI using a configuration file:

```
swa --config bar/baz/swa-cli.config.json start app
```

The `appLocation` is set to the current working directory (`./`) which breaks the lookup algorithm for `staticwebapps.config.json`, workflow files, and other flags constructions, such as `outputLocation`.

**To Reproduce**
1. create a config file  under `/tmp/foo/bar/baz/swa-cli.config.json` with the following content:
```json
{
  "configurations": {
    "app": {
      "context": "./app"
    }
  }
}
```
1. cd into `/tmp/foo`
1. type command `swa --config bar/baz/swa-cli.config.json start app`
1. See error:
![image](https://user-images.githubusercontent.com/1699357/158355225-fb73da29-6b8a-4687-96a4-a47f0516ee19.png)

**Expected behavior**

The SWA CLI is looking for the `./app` folder inside the current working directory `/tmp/foo/` instead of `/tmp/foo/bar/baz/`.

**Comment by sinedied** [comment]
I'll have a look
