### ISSUE TITLE
Evaluate lite-server

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#42]
As an alternative to `http-server`, we could evaluate [`lite-server`](https://github.com/johnpapa/lite-server) and see if we can easily use it instead of `http-server`.

**Comment by manekinekko** [comment]
@johnpapa do you recommend using this package? 😉

**Comment by johnpapa** [comment]
It works! :)

It has not been updated in a long time, but still works. I'd be happy to accept any PRs if you feel it needs any.

Effectively, lite-server combines a web server (like http-server) with a fallback package. So it's quite simple if you look at the code. Or you could create your own package. Or find another.

**Comment by manekinekko** [comment]
Thanks for the feedback @johnpapa 👍🏼

**Comment by manekinekko** [comment]
Closing in favor of #102
