### ISSUE TITLE
--api-location & --output-location should be under --app-location

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#439]
Should we prevent users from setting the context in a different folder than the API location, or output location?

Currently, the following command is valid and will not throw:

```
swa start /path/to/app --api-location /another/path/to/api --output-location /yet/another/path/to/output
```

**Comment by sinedied** [comment]
Actually, after some clarification only `outputLocation` should be under `appLocation`, `apiLocation` path is independant
