### ISSUE TITLE
(NoRegisteredProviderFound) No registered resource provider found

### ISSUE THREAD

**Issue by JonBoxTN** [Azure/static-web-apps-cli#448]
AZ CLI version: 2.35.0

Environment:
React app + MSAL, SWA w/ AD authentication, byo function connected to API, with AD App registration.  Azure DevOps, via YML and BICEP.  In EastUS2.

BICEP to create:
resource staticWebApp 'Microsoft.Web/staticSites@2020-12-01' = {
  name: '${longPrefixName}webapp'
  location: paramLocation
  sku: {
    name: 'standard'
    tier: 'standard'
  }
  properties: {
    
    buildProperties: {
      apiLocation: ''
      skipGithubActionWorkflowGeneration: true
    }
  }
  dependsOn: [
    functionApp
  ]
}

Bug: attempts to link or get information about the link relationship with the BYO functions produce various AZ CLI faults, that say:
_(NoRegisteredProviderFound) No registered resource provider found for location 'eastus2' and API version '2021-03-01' for type 'staticSites/userProvidedFunctionApps'. The supported api-versions are '2020-12-01'. The supported locations are 'westus2, centralus, eastus2, westeurope, eastasia'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'eastus2' and API version '2021-03-01' for type 'staticSites/userProvidedFunctionApps'. The supported api-versions are '2020-12-01'. The supported locations are 'westus2, centralus, eastus2, westeurope, eastasia'._

**To Reproduce**
- "az staticwebapp functions show" produces this error
- "az staticwebapp functions link" produces this error

Linking via the portal interface works.

**Additional context**

**Comment by manekinekko** [comment]
Hi, I am sorry to hear you are having issues with the Azure CLI. This issue is not related to the Static Web Apps CLI. 

The Azure CLI lives in this other repo: https://github.com/Azure/azure-cli. 

I am going to close this issue. 
Thank you.
