### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase') on @azure/static-web-apps-cli/dist/core/deploy-client.js:149

### ISSUE THREAD

**Issue by julienmourgues** [Azure/static-web-apps-cli#462]
Context : 
`swa --version` = 0.8.3
dependency npm : "@azure/static-web-apps-cli": "github:Azure/static-web-apps-cli#ga"

**Describe the bug**
Use command npx swa deploy ./dist/my-first-project --verbose=silly --deployment-token <value_token>
Ok on April 13 but KO on May 02 (without changes). Reproduce in two environnement : on Jenkins and localhost

**To Reproduce**
1. Type in command 'snpx swa deploy ./dist/my-first-project --verbose=silly --deployment-token <value_token>'
2. See error

**Expected behavior**
No error.
Actual error : 
`10:32:42  [/home/jenkins/agent/workspace/re-static-webapp_snapshot_master/node_modules/@azure/static-web-apps-cli/dist/core/deploy-client.js:149](mailto:/home/jenkins/agent/workspace/re-static-webapp_snapshot_master/node_modules/@azure/static-web-apps-cli/dist/core/deploy-client.js:149)
10:32:42              const releaseChecksum = release.files[platform].sha256.toLocaleLowerCase();
10:32:42                                                                     ^
10:32:42  
10:32:42  TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')
10:32:42      at WriteStream.<anonymous> (/home/jenkins/agent/workspace/re-static-webapp_snapshot_master/node_modules/@azure/static-web-apps-cli/dist/core/deploy-client.js:149:68)
10:32:42      at WriteStream.emit (node:events:532:35)
10:32:42      at finish (node:internal/streams/writable:754:10)
10:32:42      at finishMaybe (node:internal/streams/writable:739:9)
10:32:42      at afterWrite (node:internal/streams/writable:504:3)
10:32:42      at onwrite (node:internal/streams/writable:477:7)
10:32:42      at node:internal/fs/streams:410:5
10:32:42      at FSReqCallback.wrapper [as oncomplete] (node:fs:801:5)`

**Comment by manekinekko** [comment]
Thank you @julienmourgues for reporting this issue. We've changed an internal API signature that was causing this issue. Can you check out the latest changes from `ga` branch (make sure you have the latest commits) and let us know again?

**Comment by julienmourgues** [comment]
Hy @manekinekko , I checked out latest changes from `ga` branch and it's solve this issue.
However, I have another error.

My Web application is an Angular (v13.3) application named 'my-first-project'

I try [deploy a front end without API](https://github.com/Azure/static-web-apps-cli/tree/ga#deploy-a-front-end-app-without-an-api) with option 1 and it's failed (see [StackTrace_1.txt](https://github.com/Azure/static-web-apps-cli/files/8609535/StackTrace_1.txt))

I try [deploy a front end without API](https://github.com/Azure/static-web-apps-cli/tree/ga#deploy-a-front-end-app-without-an-api) with option 2 and it's failed (see [StackTrace_2.txt](https://github.com/Azure/static-web-apps-cli/files/8609543/StackTrace_2.txt))

On April 13 I try I try [deploy a front end without API](https://github.com/Azure/static-web-apps-cli/tree/ga#deploy-a-front-end-app-without-an-api) with option 2 and it's run (see [StackTrace_3.txt](https://github.com/Azure/static-web-apps-cli/files/8609548/StackTrace_3.txt))

Thanks in advance.

**Comment by julienmourgues** [comment]
Hi @sinedied ! I checked latest changes from `ga`, it rocks ! Thanks for fixes. I close this issue. Have a nice day.
