### ISSUE TITLE
Simulate authentication page

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#47]
**Describe the solution you'd like**

Instead of directly integrating with all supported providers, use a simulated login page that allows a user to specify the provider, user info, and roles that they want to log in as.

When the app navigates to `/.auth/<provider>/login`, display the following screen:

![image](https://user-images.githubusercontent.com/3982077/104953628-9de7dd80-597b-11eb-8b90-1a7368d54df5.png)

(the `anonymous` and `authenticated` roles are always included when authenticated)

Upon "login", store the provided information in a cookie. When an API endpoint is accessed, add a `x-ms-client-principal` header using the identity from this cookie.

Accessing `/.auth/me` returns the info from this cookie.

`/.auth/logout` clears this cookie.

**Comment by manekinekko** [comment]
Notes from last meeting with Anthony Chu and Mitali Karmarkar:

- provider input are simple free text input (no validation). Default it to the current route.
- store state in localStorage
- cookie format remains the same. Entries: userId, userName, provider, userDetails.
- auth should just redirect to callback.
- roles are stored in cookie.
- current cookie format:
```
{​​
  "clientPrincipal": {​​
    "identityProvider": "github",
    "userId": "c017e8557def49f9bec3e0f011fdf746",
    "userDetails": "anthonychu",
    "userRoles": [
      "anonymous",
      "authenticated"
    ]
  }​​
}
```​​
