### ISSUE TITLE
Usage of $schema in staticwebapp.config.json causes warning

### ISSUE THREAD

**Issue by SIkebe** [Azure/static-web-apps-cli#489]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
#454 introduced validation for `staticwebapp.config.json`. This causes warning if you define `$schema` in your `staticwebapp.config.json`.

**To Reproduce**

1. Add `$schema` to your `staticwebapp.config.json`.
2. Run `swa start`
5. See warning

**Expected behavior**
No warning will be shown if you have `$schema` section in your `staticwebapp.config.json` file.

**Screenshots**
![image](https://user-images.githubusercontent.com/17608272/169181326-ce2da2db-5086-480a-87f8-0715ee5f96b6.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser N/A
- Version: 1.0.0

**Additional context**

**Comment by manekinekko** [comment]
Hey @SIkebe thank you for reporting this issue. For now, you can simply ignore this warning for now. The team will work on publishing an updated version of the schema.

cc @Reshmi-Sriram

**Comment by anthonychu** [comment]
Fixed by https://github.com/SchemaStore/schemastore/pull/2261

**Comment by SIkebe** [comment]
Thanks!
