### ISSUE TITLE
Support Oryx environment vars

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#5]
Allow SWA EMU to use Oryx env vars from https://github.com/microsoft/Oryx/blob/master/doc/configuration.md#oryx-configuration

**Comment by manekinekko** [comment]
We are probably going to skip this for now.

**Comment by Reshmi-Sriram** [comment]
@manekinekko - is this something we are considering exploring anymore?

**Comment by manekinekko** [comment]
We are going to drop this idea, since we are not using Oryx locally.
