### ISSUE TITLE
SWA CLI documentation improvement

### ISSUE THREAD

**Issue by Ensar025** [Azure/static-web-apps-cli#502]
Not really a bug, I chose the bug option as it was the one most fitting.

**Describe the bug**
Using `swa deploy --app-location ./packages/frontend --output-location ./packages/frontend/dist` gives the error `The folder "/home/runner/work/***/***/packages/frontend/packages/frontend/dist" is not found. Exit`. 

This shows that the output location is relative to the app location. This is not noted (or at least, wasn't clear) in [the documentation](https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy/#options).

**To Reproduce**

1. Go to the root of your monorepo project
2. Type in the command `swa deploy --app-location ./packages/frontend --output-location ./packages/frontend/dist`
3. See error

**Expected behavior**
After reading the documentation, I expected that the output location would not be relative to the app location. In my opinion, it makes sense that it is, the documentation just needs to be updated to be more clear.

**Desktop (please complete the following information):**
- OS: macOS
- Version 12.2.1

**Comment by Reshmi-Sriram** [comment]
Hey @Ensar025,

Thanks for pointing it out, will add this to the docs! :)
