### ISSUE TITLE
error: unknown option '--subscription'

### ISSUE THREAD

**Issue by adriancuadrado** [Azure/static-web-apps-cli#504]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

N/A

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When I run `swa login --subscription <subscription-id>` I get this error: `error: unknown option '--subscription'`, but `swa login --help` says it should be `subscription`

**To Reproduce**

1. Run `swa login --help` and see how the help says the parameter is `--subscription`
2. Run `swa login --subscription <subscription-id>`
3. See how it says  `error: unknown option '--subscription'`

**Expected behavior**
Either the help should say its `subscription-id` or the option should be changed from `subscription-id` to `subscription`.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
N/A

**Comment by Reshmi-Sriram** [comment]
Hey @adriancuadrado,
Thanks for bringing this to our attention. Looks like we made a small typo. Will fix it ASAP!
