### ISSUE TITLE
Invalid environment value deploys to production

### ISSUE THREAD

**Issue by Ensar025** [Azure/static-web-apps-cli#508]
Using SWA version: 1.0.1

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
Deploying the SWA using `swa deploy --app-location ./packages/frontend --api-location ./packages/api --env no-src` deploys to Production even though it gives an error saying `✖ The environment name provided has invalid character(s). Valid characters are 0-9, a-z, and A-Z`.

Screenshot of terminal when executing the command (I also included a date to show that it is around that timeframe. Laptop is kind of slow so it takes a bit to execute the script):
<img width="855" alt="image" src="https://user-images.githubusercontent.com/99197230/170045723-6fc617ec-874d-4c2d-91f0-eae15ddbd6a0.png">

Screenshot of Azure SWA environments:
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/99197230/170047619-609ab54b-39c9-4e2f-b331-99d574983d05.png">

**To Reproduce**

1. Create SWA app
2. Type in command `swa deploy --app-location ./packages/frontend --api-location ./packages/api --env no-src`
3. See error: `✖ The environment name provided has invalid character(s). Valid characters are 0-9, a-z, and A-Z`
4. View Azure dashboard and see deployment to Production is in progress

**Expected behavior**
A deployment to Production should not happen if the environment name variable syntax is wrong

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.2.1

**Comment by sgollapudi77** [comment]
Thanks @Ensar025 for pointing this out, we will look into this.

**Comment by Timothyw0** [comment]
Closing this issue as it has been fixed in CLI v1.1.6 and mentioned in https://github.com/Azure/static-web-apps-cli/issues/785
