### ISSUE TITLE
Setup a release pipeline for @azure/static-web-apps-cli

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#51]
Current package is published under [@manekikko/swa-emu](https://www.npmjs.com/package/@manekinekko/swa-emu).

We'd like to move it under @azure/static-web-apps-cli.

**Comment by manekinekko** [comment]
@anthonychu I think this issue can be closed now that we have our release pipeline working.

**Comment by anthonychu** [comment]
Yep this was addressed with #122. I still need to add the release instructions though.

**Comment by Reshmi-Sriram** [comment]
This issue is resolved.
