### ISSUE TITLE
swa deploy - Cannot see logs when there's an error

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#514]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

Trying to use swa deploy. It's failing but it's not possible to see the details of the deployment. It just shows `An unknown error has occurred`.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/3982077/171911107-0539e187-db20-432d-ad63-bbaf3e9336d5.png">

**Comment by Reshmi-Sriram** [comment]
Hey @anthonychu,
Is this related to #500? Could you confirm if you tried the steps mentioned there? We are investigating the fix currently, but need more clarity on whether the error we see in your case is different from that mentioned in the #500 issue or not. Thanks!

cc// @sgollapudi77

**Comment by thomasgauvin** [comment]
@anthonychu @Reshmi-Sriram I am experiencing the same `An unknown exception has occured` at the same moment as mentioned here https://github.com/Azure/static-web-apps-cli/issues/500#issuecomment-1132738190

**Comment by sgollapudi77** [comment]
Hey @anthonychu , is it possible to share your repo? I'm also facing the same issue and I want to confirm if the same is happening for you also.

There are two cases, 

** Case 1 ** : Folder structure looks something like this and tried 'swa deploy ./app --api-location ./api' -> `Deploy works fine`
- /src
   - /api
   - /app
      - index.html
      - index.js
   
** Case 2 ** : Folder structure looks like this and tried 'swa deploy . --api-location ./api' -> `Deploy fails with Unknown exception occured`
- /src
   - /api
   - index.html
   - index.js

**Comment by sgollapudi77** [comment]
Hey, we're experiencing the same error on our end too and this issue is being actively worked on. But fortunately, we have a workaround for this. If you're deploying from the root folder where your app contents are present, please try creating a folder for app_location and dump your static contents in that folder and do 'swa deploy'.

We also documented the same [here](https://azure.github.io/static-web-apps-cli/docs/contribute/Troubleshooting#swa-deploy---current-caveat).

**Comment by wowq** [comment]
I need the same error report, but I am running in Docker, which is related to the file permissions. It should be that new files cannot be created during compression

**Comment by thomasgauvin** [comment]
@sgollapudi77 to your point, I'm encountering this issue when trying to deploy my built (/dist) folder from SWA CLI. The repo is https://github.com/thomasgauvin/solidjs-starter. The command I'm executing is `swa deploy ./dist`

Funnily enough, it worked the first time I submitted the deployment, but when I wanted to redeploy, it gave me the error.

**Comment by wowq** [comment]
It seems to have something to do with not running cli in the **/bin/staticwebsites/** directory. In my project, if you do not run cli in this directory, an error will be reported

**Comment by sgollapudi77** [comment]
We did a new StaticSiteClient release recently, can you please check once and get back to us if you find any issue. Thanks.
This issue is related to #557

**Comment by sgollapudi77** [comment]
Closing this issue as it is related to #557 , feel free to track this at the parent.
