### ISSUE TITLE
Serving urls without .html extension

### ISSUE THREAD

**Issue by betfix** [Azure/static-web-apps-cli#535]
On my static website (with many pages, not a SPA), after running 'swa start' on local PC, the `http://localhost:4280/posts/mypost.html` returns 200, but the `http://localhost:4280/posts/mypost` returns 404. Adding a rewrite to staticwebapp.config.json helps for this particular path:

```
"routes": [
     {
       "route": "/posts/mypost",
       "rewrite": "/posts/mypost.html"
     }
   ]
```

However:
1) This is an obvious task and the file could become large to rewrite all pages (unless there is an option to rewrite all-in-one line which I don't find)
2) website deployed to Azure with 'swa deploy' works fine without any rewrites.

So I think such feature would be good to have as a configuration option.

**Comment by sgollapudi77** [comment]
Hey @betfix , as per the official Static Web Apps [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#trailing-slash), whenever trailing slash configuration is omitted in staticwebapp.config.json, /posts/mypost will redirect to /posts/mypost.html. However this behaviour is not supported currently in SWA_CLI. There is an open issue #418 for tracking the same. This item is in our backlog and we'll start working on this soon.

**Comment by sgollapudi77** [comment]
Closing this issue and keeping the original issue open - #418
