### ISSUE TITLE
Not able to insert the connectionstring with "&" charecter

### ISSUE THREAD

**Issue by anirugu** [Azure/static-web-apps-cli#551]
I am using Win10 VS 2022 Preview with .net 6 (this is nowhere needed but giving for better clue).

I am facing a problem in CLI. I want to import the appsettings through cli commands, I tried

```
az staticwebapp appsettings set -n anirudhagupta4september1040 --setting-names MONGO_CONNECTION_STRING="commentedforprivacy/?retryWrites=true&w=majority"
```
This is giving me error 

```
'w' is not recognized as an internal or external command,
operable program or batch file.
```
I check the value in the portal and seeing that it's missing '&w=majority' from the connectionstring. When I search on internet I found this https://github.com/Azure/azure-cli/issues/16431

Using double quote and ("") doesn't help. Like it's mention in given links. I am looking for workaround.

1. Is there a way I can do this in CLI. like some special way other than double quote or ("").
2. Is there a way I can handle this in github workflow. 
Or any other background which doesn't required c# and can be done through code.

**Comment by sulabh-msft** [comment]
This looks like an issue in az cli . @Reshmi-Sriram probably we should move the the request to aure-cli project.

**Comment by sgollapudi77** [comment]
This is an Az-cli issue. @anirugu kindly re-open the issue with the [az-cli team](https://github.com/Azure/azure-cli/issues/16431)

**Comment by anirugu** [comment]
For anyone who is facing this issue,

I found that bash is more potent than cmd/Powershell, therefore there is 2 workaround.

1. either run it in git bash.
2.  run it in the cloud shell in the Azure portal.
