### ISSUE TITLE
Missing npm run dev command in the swa-cli-config.json (Next.Js applications)

### ISSUE THREAD

**Issue by glaucia86** [Azure/static-web-apps-cli#553]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When I use the command **swa init** generates me a **swa-cli.config.json** file (under any Next.Js project) a default configuration to execute the NextJs app + SWA CLI Tool.

But in the dev command appears as: **npm dev**. But the correct way should be: **npm run dev**

**To Reproduce**

1. Generates any Next.js project
2. Type the command 'swa init'
3. the 'swa-cli.config.json' will be generated
5. See error (as the image above)

**Expected behavior**
But in the dev command appears as: **npm dev**. But the correct way should be: **npm run dev**

**Screenshots**
![image](https://user-images.githubusercontent.com/1631477/189166010-d37bb5db-efdc-46aa-b4ad-7cc0456ec64b.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Node.Js version: 16.x

**Additional context**

**Comment by glaucia86** [comment]
@Reshmi-Sriram I found this issue. I will fix it tomorrow! ;)

**Comment by sgollapudi77** [comment]
Thanks for the fix @glaucia86. Closing this now.
