### ISSUE TITLE
Proxy SWA /api to other backends 

### ISSUE THREAD

**Issue by thomasgauvin** [Azure/static-web-apps-cli#567]
Add support for proxying SWA CLI /api to other backends. If I'm developing a SWA with an Express backend (for instance) and intend to deploy to App Service with /api integration, I should be able to develop locally with /api proxy to my express backend. 

This is an ask from the community as well: https://stackoverflow.com/questions/73765847/how-to-access-secured-api-management-apis-linked-to-an-azure-static-web-applicat

**Comment by thomasgauvin** [comment]
Just tested this on 1.0.4 and it's now supported. From my investigation, this was supposed to be working previously but a bug (which was fixed with [1.0.4](https://github.com/Azure/static-web-apps-cli/releases/tag/v1.0.4)) has resolved this. 

Can we promote that we now support other types of backends with SWA CLI? @manekinekko @sgollapudi77 @annikel

**Comment by thomasgauvin** [comment]
I am closing this issue as it is working.

**Comment by njrardin** [comment]
Sorry to bring this up again but is there anywhere where it's described *how* to do this? My web searches keep bringing me back here only to be told that it's a thing which can be done....with no way to figure out how to do it.
