### ISSUE TITLE
File not found (403) - Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe@1.0.020761 

### ISSUE THREAD

**Issue by kunukn** [Azure/static-web-apps-cli#576]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [ X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
Console output

```
Deploying to environment: production

Deploying project to Azure Static Web Apps...
StaticSitesClient is outdated! Expected 1.0.020761, got 1.0.019361
[swa] ✖ Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe@1.0.020761
✖ 
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary. File not found (403)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
```

**To Reproduce**

1.  swa deploy ./dist/  -n NAME --env production --deployment-token TOKEN

The given url https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe@1.0.020761 gives me
```
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:5bc7a37a-201e-00a4-17d3-d3add7000000 Time:2022-09-29T07:16:06.4365437Z</Message>
</Error>
```

**Expected behavior**

Deployment succeeded

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10

**Additional context**

**Comment by manekinekko** [comment]
Hi @kunukn the correct url is  https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe. The `@version` prefix is only used for logging. 

Are you able to access that binary manually from you browser? Have you checked your firewall, it is probably blocking the SWA CLI?

**Comment by kunukn** [comment]
It seems to be my corporate firewall that blocks this.

I got a screen warning when trying the url in the browser.

```
You tried to visit: https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe

You are downloading exe64 filetype from a site categorized as Web Host...

Please be aware that the usage of this application has not been evaluated by ..
```

**Comment by kunukn** [comment]
Do anyone have insights on where to manually update `StaticSitesClient.exe`
If I have the new version. Where should it be placed? How do we install a new version of `StaticSitesClient`?

**Comment by manekinekko** [comment]
Hi @kunukn , here is a temporary manual process to install the binary and use the binary. We will simplify it in the future.

**NOTE: This is how the SWA CLI automatically downloads and configures the deploy binary**

1. Visit https://swalocaldeploy.azureedge.net/downloads/versions.json
1. Copy the `stable` JSON content, for eg:
```json
{
    "version": "stable",
    "buildId": "1.0.020761",
    "publishDate": "2022-09-07T17:34:35.4261936Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.020761/linux/StaticSitesClient",
        "sha": "871ae9f154ddb8123e24c507e39dfc11c99f34815e59b178051a6e44a870e308"
      },
      "win-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe",
        "sha": "360b76959c68cc0865b1aea144c8eb2aa413f4856e55c781a83bd7e1ad352362"
      },
      "osx-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.020761/macOS/StaticSitesClient",
        "sha": "1a90511003609af378ff3628feaf3115f9d7e335085a925045e9f206359fdb90"
      }
    }
  }
```

1. Based on your operating system, download the right binary from the provided URLs:
   1. Linux: https://swalocaldeploy.azureedge.net/downloads/1.0.020761/linux/StaticSitesClient
   2. Windows: https://swalocaldeploy.azureedge.net/downloads/1.0.020761/windows/StaticSitesClient.exe
   3. macOS: https://swalocaldeploy.azureedge.net/downloads/1.0.020761/macOS/StaticSitesClient

1. Copy this binary to `$HOME/.swa/deploy/VERSION/StaticSiteClient` (add `.exe` for Windows). For eg:
   `/home/USER/.swa/deploy/1.0.020761/StaticSiteClient`

1. Create a file at `$HOME/.swa/deploy/StaticSitesClient.json` with the following content:
```json
{
   "metadata": PASTE STABLE JSON CONTENT,
   "binary": "ABSOLUTE PATH TO STATIC SITE CLIENT BINARY",
   "checksum": "SH256 CHECKSUM OF THE BINARY"
}
```

For eg: 
```json
{
   "metadata": {
    "version": "stable",
    "buildId": "1.0.020761",
    ...
  },
   "binary":"/home/USER/.swa/deploy/1.0.020761/StaticSitesClient",
   "checksum":"871ae9f154ddb8123e24c507e39dfc11c99f34815e59b178051a6e44a870e308"
}
```
**IMPORTANT: Make sure the `StaticSitesClient.json#checksum` and `StaticSitesClient.json#metadata.files.[OS].sha` values match!**

1. Run `swa deploy --verbose silly` and make sure `SWA_CLI_DEPLOY_BINARY` is set correctly. If everything was configured correctly, the deploy should work.

**Comment by kunukn** [comment]
Thank you very much. I can confirm it works on my Windows 10.

**Comment by manekinekko** [comment]
Good to hear 😊

**Comment by sgollapudi77** [comment]
Thanks @manekinekko , closing this issue now.
