### ISSUE TITLE
`swa login -cc` is not working

### ISSUE THREAD

**Issue by doggy8088** [Azure/static-web-apps-cli#589]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**

After I logined into Azure using `swa login`. I can use `swa login --clear-credentials` to login again. But when I use `swa login -cc` command, it's not working.

![image](https://user-images.githubusercontent.com/88981/196513981-81cdb56d-fae8-4e28-b0e0-1930a3a25127.png)

**To Reproduce**

1. `swa login`
2. `swa login -cc`

**Expected behavior**

I expected `swa login -cc` should open browser for sign-in process.

**Screenshots**

![image](https://user-images.githubusercontent.com/88981/196513704-58addf70-28fe-4ae5-a3da-de0b211b2403.png)

**Desktop (please complete the following information):**

- OS: `Windows 10`
- Version: `10.0.19043.2130`

**Additional context**

**Comment by doggy8088** [comment]
I think you might able to implement `swa logout` for this. Sometimes I just want to logout to clear Azure credential cache.

**Comment by doggy8088** [comment]
Here is the way to clear all credentials created by swa-cli:

PowerShell

```ps1
cmdkey.exe /list | findstr swa-cli | ForEach-Object {
  cmdkey /delete:$($_.Split(' ')[5])
}
```

**Comment by rupareddy5-21** [comment]
Hi @doggy8088, thanks for pointing this out, we have found the root cause and created a PR for the fix. The flag -cc is not working because -c is a [global option](https://azure.github.io/static-web-apps-cli/docs/cli/swa/#options) for swa-cli.config.json path and that is taking priority when -cc flag is used. For fixing this, we have changed the short-form of flag from -cc to -CC. Sorry for the inconvenience caused.

**Comment by doggy8088** [comment]
@rupareddy5-21 Are you consider to have a `swa logout` subcommand?

**Comment by Reshmi-Sriram** [comment]
> @rupareddy5-21 Are you consider to have a `swa logout` subcommand?

Hi @doggy8088, this is a great suggestion. Currently the team is working towards supporting the clear credentials flag. Could you help us understand better on whether you would still be looking for a `swa logout` option? We can definitely pick it up if the current support for `clear-credentials` is not enough. Thanks!

**Comment by doggy8088** [comment]
@Reshmi-Sriram I tried latest version today. (`1.1.6`)

I still think the `swa logout` still required. Right now, the `-CC` or `--clear-credentials` option is to clear persisted credentials before login. But the use case could be someone login at other's or public computer. After been deployed, I simply want a "LOGOUT" to clear credential. What do you think?
