### ISSUE TITLE
deploy command fails when there are large amount files

### ISSUE THREAD

**Issue by kevin-george-ul** [Azure/static-web-apps-cli#611]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**

When trying to deploy a static-site with just HTML content and no API, the `swa deloy` command completes without error, stoping execution at this log line "DeploymentId: 66a0514d-24c1-47cf-b271-33f22ac672d4"

**To Reproduce**

1. Open a Terminal
2. Create a folder called web `mkdir web`
3. Create an index.html file `"<html><body><h1>Hello world Index</h1></body></html>" | Out-File -Encoding utf8 -FilePath "web\index.html"`
4. Generate 17K HTML files, for example you can use: `0..17000 | ForEach-Object -Parallel { "<html><body><h1>Hello world $_</h1></body></html>" | Out-File -Encoding utf8 -FilePath "web\$_.html" }`
5. `swa init` / create an swa-cli.config.json file as below 
6. `swa deploy --verbose=silly  --env production`, this fails without any error ❌
7. Keep 1000 files (_or remove 16K_) `gci .\web\ | Where-Object -Property BaseName -NE 'index' | Where-Object { [int]$_.BaseName -ge 1000} | Remove-Item`
8. Deploy again 
9. `swa deploy --verbose=silly  --env production`, this work ✅

**swa-cli.config.json**
```json
{
  "$schema": "https://aka.ms/azure/static-web-apps-cli/schema",
  "configurations": {
    "web": {
      "appName": ".....",
      "resourceGroupName": ".....",
      "outputLocation": "web"
    }
  }
}
```

**Expected behavior**
The files are deployed as expected 

**Screenshots**

**❌ Failure** - With 17K files, the log completes without any warning/error
![image](https://user-images.githubusercontent.com/91074239/203842357-77baaf42-fe58-4a22-bc7c-5c99ca6e05c9.png)

**✔ Success** - with 1K files it completes without issue
![image](https://user-images.githubusercontent.com/91074239/203842817-bbee75c9-9066-4901-8bb3-3bb7996380d6.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise
- Version 21H2 

**Additional context**

**Comment by sgollapudi77** [comment]
Hey @kevin-george-ul, there is a limitation of 15000 files in the Static Web App. This is the limitation of SWA itself hence you cannot deploy app with more than 15000 files to Static Web app. There is an open issue in the Static Web apps repo for tracking this, please check it there. [Issue#520](https://github.com/Azure/static-web-apps/issues/520)

**Comment by kevin-george-ul** [comment]
@sgollapudi77 , if you can - could you please add your feedback to this too

https://github.com/MicrosoftDocs/azure-docs/issues/102099
