### ISSUE TITLE
Angular i18n deploy

### ISSUE THREAD

**Issue by chris-consulting** [Azure/static-web-apps-cli#612]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x ] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
I have an Angular i18n application to deploy.
The dist folder structure is:
-dist\app_name\[en|fr|de] . It means there is no index.html under the folder dist\app_name.  I run swa deploy dist\app_name --deployment-token xxxx
The deployment is successfully, but nothing is deployed

**To Reproduce**
- Create a i18n Angular application with at least 2 locations
- run swa build
- run swa deploy  dist\app_name --deployment-token xxxx
- The application is not deployed

**Expected behavior**
- Either an error message: "no index.html, cannot deploy"
- or the application to be deployed as there are index.html in en or fr folder.

**Additional context**
- there is a workaround: you can automatically copy an index.html after the swa deploy command

**Comment by sgollapudi77** [comment]
Hey @chris-consulting, there is already an issue where swa-deploy fails without logs #557. We made changes in our backend to print the error logs and that change is deployed yesterday. Can you please check and confirm if you're still facing this problem

**Comment by Reshmi-Sriram** [comment]
Hi @chris-consulting, could you please confirm if you are still facing issues?

**Comment by chris-consulting** [comment]
It was a time out, due to the bandwidth where I was. The message was not clear at all. I upload the build on a VM, I did not check the message was better.

**Comment by Reshmi-Sriram** [comment]
Apologies for the experience! We worked on improving the error logs visibility and hopefully it helps unblock folks faster going forward!
Thanks for confirming it works fine! Closing this issue.
