### ISSUE TITLE
Deployment fails because the project is linked to "SwaCli" provider

### ISSUE THREAD

**Issue by sgollapudi77** [Azure/static-web-apps-cli#622]
**Describe the bug**
✖ The project "$proj" is linked to "SwaCli"!
✖ Unlink the project from the "SwaCli" provider and try again.

**To Reproduce**

`swa deploy` to an already existing app linked to SwaCli fails.

**Expected behavior**
Deployment should happen without any error.

**Comment by sgollapudi77** [comment]
This is a known issue and the fix for this is already merged to the repo, however we're blocked on doing a new release. So, please hold on us for a couple of days and we'll be doing a new release.

**Comment by anujb** [comment]
@sgollapudi77 what's the workaround for this regression?

**Comment by sgollapudi77** [comment]
Hi @anujb , you can deploy to a new SWA for now which should ideally solve the problem.

**Comment by sgollapudi77** [comment]
We released a [new version](https://www.npmjs.com/package/@azure/static-web-apps-cli/v/1.0.4) now. Now you shouldn't face this error. Please check now @anujb

**Comment by arpanD93** [comment]
facing similar issue even though using SWA 1.1.10. How do I unlink from github repo? There's no option available in Azure portal. 


Checking project settings...
√ Choose your Static Web App » dev-XXXXXXX-rg/dev-XXXXXXXX
✖ The project "dev-XXXXXXX" is linked to "GitHub"!
✖ Unlink the project from the "GitHub" provider and try again.
PS C:\Scripts\Hygeia\app> swa --version
1.1.10
PS C:\Scripts\Hygeia\app>

**Comment by felaray** [comment]
Checking project settings...
√ Choose your Static Web App » H*****/H*****
✖ The project "H*****" is linked to "GitHub"!
✖ Unlink the project from the "GitHub" provider and try again.  
PS C:\H*****> swa -v
2.0.6

**Comment by tim-mcqueen-ttec** [comment]
> Checking project settings... √ Choose your Static Web App » H*****/H***** ✖ The project "H*****" is linked to "GitHub"! ✖ Unlink the project from the "GitHub" provider and try again. PS C:\H*****> swa -v 2.0.6

az staticwebapp disconnect --name <app name>
