### ISSUE TITLE
SWA CLI cannot login with a Microsoft account

### ISSUE THREAD

**Issue by TechWatching** [Azure/static-web-apps-cli#645]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

1.0.6

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [ X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When doing an `swa login` and connect using my Microsoft account login, the login fails with the following message: `ERROR. Scopes: https://management.azure.com//.default. Error message: null. null.`

**To Reproduce**

1. Go to 'the terminal
2. Type in command 'swa login'
3. Enter credentials of a Microsoft account and click sign in

**Expected behavior**
The SWA CLI should be able to login to Azure using a Microsoft account.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 10/0/22000

**Comment by sgollapudi77** [comment]
Hey @TechWatching, can you try it now and get back to us. We faced this error sometime back but now it is working fine. Thanks.

**Comment by TechWatching** [comment]
Still the same issue: 

![image](https://user-images.githubusercontent.com/15186176/214256688-22ca7aac-f4e2-4566-9c1f-593e020e675b.png)

I am using a live.com account

**Comment by sgollapudi77** [comment]
Hey @TechWatching this issue has been resolved on the azure-identity team, can you check once and see if it still persists?

**Comment by TechWatching** [comment]
Same issue. Should I upgrade the swa CLI to something?

**Comment by DeadDuck** [comment]
Any progress? Does it normally work?

We are having the same issue with v1.1.6 in Windows 11, making it useless for us.

When tried to login or deploy, the browser instantly displays:
`ERROR. Scopes: https://management.azure.com//.default. Error message: null. null.`

And in the CLI we instantly get the error as below:

![image](https://github.com/Azure/static-web-apps-cli/assets/474456/68d319cc-7c0d-430f-a9a2-ec1eaaf32270)

**Comment by DeadDuck** [comment]
I used the deployment token for the deployment, bypassing interactive login, and it works for me.

**Comment by cveld** [comment]
Would be great if `swa login` would support az cli auth, or device token auth.

**Comment by adrianhall** [comment]
Hi all,

I have tested this with the latest Azure CLI + SWA CLI 1.1.10, and it seems to be working now using my outlook.com credentials.  (At least, I cannot reproduce).  We have other issues open for properly supporting AzureCLI and DeviceAuth tokens.

If anyone is still having problems, please open a new issue and be sure to include your environment (Node version, OS version, etc.)
