### ISSUE TITLE
swa deploy throwing error reason: getaddrinfo ENOTFOUND swalocaldeploy.azureedge.net

### ISSUE THREAD

**Issue by ABL6COB** [Azure/static-web-apps-cli#647]
swa cli version 1.0.6

**Describe the bug**
I am trying to run the swa cli from my local machine and publish to a static webabb.
I have login to azure using Service principle and The command I use is,
swa deploy --verbose silly --app-location [appLocation] --deployment-token [deploymentToken] --env [envName] --api-location [apilocation] --swa-config-location [configFileLocation]

I get the below error,
 Deployment Failed :(
✖ Deployment Failure Reason: request to https://swalocaldeploy.azureedge.net/downloads/versions.json failed, reason: getaddrinfo ENOTFOUND swalocaldeploy.azureedge.net
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose

I checked in internet and found this : https://azure.github.io/static-web-apps-cli/docs/contribute/Troubleshooting/#unable-to-download-staticsitesclient-binary-file-not-found-404---403
But the site "https://swalocaldeploy.azureedge.net/downloads/1.0.020761/linux/StaticSitesClient" is showing "BlobNotFound" when we try to access it.

**Expected behavior**
The deployment should happen without any issue.

**Comment by ABL6COB** [comment]
I have downloaded the 1.0.021731 and did the steps mentioned in [here](https://azure.github.io/static-web-apps-cli/docs/contribute/Troubleshooting/#unable-to-download-staticsitesclient-binary-file-not-found-404---403). But still getting the below error,

WARNING: Failed to load staticwebapp.config.json schema. Continuing without validation!
Deploying project to Azure Static Web Apps...
Could not read StaticSitesClient metadata: SyntaxError: Unexpected token   in JSON at position 2
Fetching release metadata for version: stable. Please wait...
✖
✖ Deployment Failed :(
✖ Deployment Failure Reason: request to https://swalocaldeploy.azureedge.net/downloads/versions.json failed, reason: getaddrinfo ENOTFOUND swalocaldeploy.azureedge.net
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose

**Comment by rupareddy5-21** [comment]
Hi, can you please share your any details of your SWA? Are you running into this issue even after multiple tries? if not, can you please retry the scenario and let me know if the issue persists because I tested the scenario and I didn't find any issue for latest and old SWACLI versions.

**Comment by ABL6COB** [comment]
Yes, after multiple tries I am still facing the issue.
I am usig 1.0.6 version.

**Comment by sgollapudi77** [comment]
Hey @ABL6COB, based on the error you're facing this issue seems to be coming because the site "swalocaldeploy.azureedge.net" is not accessible. Did you try allowlisting these [domains](https://azure.github.io/static-web-apps-cli/docs/contribute/Troubleshooting/#swa-cli---domains-that-need-firewall-access)? If not, can you check if your firewall is blocking these domains.

Another workaround I can provide is the [link](https://azure.github.io/static-web-apps-cli/docs/contribute/Troubleshooting/#unable-to-download-staticsitesclient-binary-file-not-found-404---403) you mentioned.
Here instead of the given JSON content, can you try creating JSON file with this content?
`{
    "version": "stable",
    "buildId": "1.0.021731",
    "publishDate": "2022-12-14T02:22:20.0230853Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.021731/linux/StaticSitesClient",
        "sha": "d2f88cf8b855169534c7e330dd95385b993b1c0f83331306e685faa8468a82b5"
      },
      "win-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.021731/windows/StaticSitesClient.exe",
        "sha": "525d13ebffd79ea9663a15a4bd2e6d49bca72d20aa44838aa4b83133943d450c"
      },
      "osx-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.021731/macOS/StaticSitesClient",
        "sha": "5de3ac4b205d3871e7a8ff3b5869f2a57002277ac7fa6317032239d114e25ab8"
      }
    }
  }`

or download the binary from the above urls instead of the one in the documentation?

**Comment by ABL6COB** [comment]
The issue is due to firewall preventing the download of https://swalocaldeploy.azureedge.net/downloads/1.0.021731/linux/StaticSitesClient. I have changed the firewall settings to allow access to it and it worked.
Thank you @sgollapudi77 for your comments. I will close this bug.
