### ISSUE TITLE
SWA automatically deploys to production if environment name is invalid

### ISSUE THREAD

**Issue by alexzimmer96** [Azure/static-web-apps-cli#650]
**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
When using swa to deploy to an environment and the environment name is invalid, swa decides to deploy to Production instead.

**To Reproduce**

1. Switch to whatever built project you want to deploy.
2. Type in command 'swa .deploy .... --env something-thats-more-then-16-characters'
3. See error that states that the environment is to long.
4. See that swa falls back to deploy to Production.

**Expected behavior**
Stopping the Process and exiting with a non-zero exitcode to indicate, that this is an error. Otherwise, when trying to deploy to dynamic environments from CI, this could lead to overwrite Production.

**Screenshots**
![image](https://user-images.githubusercontent.com/7714821/216631223-3275ea52-7288-4b61-92f6-337595191f8c.png)

**Desktop (please complete the following information):**
- Run was in Gitlab-CI using the hosted Docker Image

**Additional context**

**Comment by rupareddy5-21** [comment]
Hi @alexzimmer96 , thanks for reporting. This is a known issue, and we are already working on the fix. Please feel free to track the issue at #508
