### ISSUE TITLE
Cannot use swa CLI on Windows 11

### ISSUE THREAD

**Issue by nguyenlamlll** [Azure/static-web-apps-cli#686]
**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When I try to run `swa start`, it fails. What I try to run:

```powershell
swa start http://localhost:5283 --run "dotnet watch run" --api-location ../Backend --verbose=silly
```

The command throws this error
```
[api] Failed to load the dll from [C:\Users\{MyUser}\.swa\core-tools\v4\hostfxr.dll], HRESULT: 0x800700C1
[api] The library hostfxr.dll was found, but loading it from C:\Users\{MyUser}\.swa\core-tools\v4\hostfxr.dll failed
[api]   - Installing .NET prerequisites might help resolve this problem.
[api]      https://go.microsoft.com/fwlink/?linkid=798306
[api] cd "C:\Users\...\Backend" && "C:\Users\{MyUser}\.swa\core-tools\v4\func" start --cors "*" --port 7071  exited with code 2147516546
--> Sending SIGTERM to other processes..
[swa] node "C:\Users\{MyUser}\AppData\Roaming\nvm\v18.16.0\node_modules\@azure\static-web-apps-cli\dist\msha\server.js" exited with code 1
--> Sending SIGTERM to other processes..
[run] cd "C:\Users\...\Frontend" && dotnet watch run exited with code 1
```

However, the projects build and work on their own (when I use `dotnet` command or with Visual Studio). I have .NET SDKs installed (I use .NET 6.0.408)

I have also tried to install kb4457144 update as someone on the Internet suggests (to fix the issue with hostfxr.dll), but my Windows 11 laptop cannot install it.

**Expected behavior**
It should run fine. I have another windows 10 PC and the same command runs fine there.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 22H2

**Comment by gyhyfj** [comment]
Same problem on win10, no matter .NET verson is 6 or 7.
node verson is v18.16.0, how to fix it?

**Comment by nguyenlamlll** [comment]
On my side, it was actually a problem with `func` command. Maybe can you check if you can `func host start` the API alone?
