### ISSUE TITLE
Emulate ACL

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#7]
Read [docs](https://docs.microsoft.com/azure/static-web-apps/authentication-authorization?WT.mc_id=-github-wachegha#role-management)

Related https://github.com/Azure/swa-emulator/issues/6

**Comment by aaronpowell** [comment]
Part of this is addressed in #11 by enforcing the `routes.json` access checks.

**Comment by manekinekko** [comment]
Roles assignment emulation will be added by #54

**Comment by manekinekko** [comment]
fixed in #44a8849
