### ISSUE TITLE
Cannot extract `DataApiBuilder` zip file on Node v18.16.0 and Windows

### ISSUE THREAD

**Issue by horihiro** [Azure/static-web-apps-cli#700]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
`swa db init` command cannot work properly with Node.js v18.16.0 (on WIndows at least)

**To Reproduce**

1. Launch Windows Sandbox
2. Install Node.js v18.16.0
3. Install SWA CLI v1.1.2
4. Execute `swa db init --database-type mssql` in any directory

**Expected behavior**
Config file `staticwebapp.database.config.json` would be generated without any error.

**Screenshots**
![image](https://github.com/Azure/static-web-apps-cli/assets/4566555/0fa0a188-de02-4f48-9e3b-9062cb867042)

The extracted executable file `Microsoft.DataApiBuilder.exe` is broken because it cannot be executed even from explorer and cmd,
![image](https://github.com/Azure/static-web-apps-cli/assets/4566555/965b1d90-b6a1-4977-97aa-3da114769e5e)

![image](https://github.com/Azure/static-web-apps-cli/assets/4566555/196a45ad-c06c-4838-bcde-5a3eebd5f206)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11

**Additional context**
This issue looks like `unzipper`'s one on Node v18.16.0, because this can be resolved by manual extraction of `dab_win-x64-x.y.z.zip`.    
https://github.com/ZJONSSON/node-unzipper/issues/271

**Comment by cjk7989** [comment]
A new version of swa-cli (v1.1.4) has been published that fixes the issue (see [#718](https://github.com/Azure/static-web-apps-cli/pull/718)). Sorry for the delay and thanks for your feedback.

**Comment by horihiro** [comment]
Thanks @cjk7989 
I confirmed that this issue was resolved with swa-cli@v1.1.4 and node.js@v18.17.0.
