### ISSUE TITLE
Docker image using incorrect version

### ISSUE THREAD

**Issue by EniacMlezi** [Azure/static-web-apps-cli#701]
**Describe the bug**
Docker container swacli/static-web-apps-cli:1.1.2 does NOT contain swa cli version 1.1.2, but version 1.1.1.

**To Reproduce**
-  docker run --rm -it swacli/static-web-apps-cli:1.1.2
-  swa -v

**Expected behavior**
Expected version to be 1.1.2

**Screenshots**
![image](https://github.com/Azure/static-web-apps-cli/assets/15785664/8b3e6cbd-48b8-46f2-9186-31b63a9933a3)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11

**Comment by cjk7989** [comment]
Thanks for your feedback. The bug is due to the docker publishing workflow, and it will be fixed in the next release : )
