### ISSUE TITLE
offline installation of swa cli will work ?

### ISSUE THREAD

**Issue by vivuu1989** [Azure/static-web-apps-cli#706]
we dont have direct connectivity to nodejs.org site from our Build agent linux machine and only Jfrog proxy repo for npm packages we are using.

We configured the jfrog settings on the repo to connect our build machine. But the  "npm install -g @azure/static-web-apps-cli" is not working.

Is there any offline installation method for swacli ?

Our requirement is to run Azuredevops server pipeline to deploy the webapps. But we couldn't find the staticwebapp task in azuredevops server and also the swa cli offline installation of getting failed is failing.

**Comment by cjk7989** [comment]
Hi @vivuu1989, could you download swa-cli manually (clone this repo) and copy it to your agent linux machine? Then you can use "npm link ./" in the local path of swa-cli to use it globally. See [developer.md](https://github.com/Azure/static-web-apps-cli/blob/main/docs/www/docs/contribute/2-developer.md).

**Comment by adrianhall** [comment]
Per the comment, you can set it up
