### ISSUE TITLE
CLI tools are downloaded for the wrong architecture on AMD Ryzen and Linux Mint

### ISSUE THREAD

**Issue by Cypher1** [Azure/static-web-apps-cli#710]
**Are you accessing the CLI from the default port `:4280` ?**
I can't access the CLI from any port.

> Make sure you are accessing the URL printed in the console when running `swa start`!

No URL is printed.

**Describe the bug**
Wrong CLI tools appear to be downloaded for my CPU arch.

**To Reproduce**

1. Open a repo on AMD Ryzen
2. Type in command 'npx @azure/static-web-apps-cli start --verbose=silly'
3. View the error message containing `SIGTERM` and `[api] /bin/sh: 1: /home/jaypratt/.swa/core-tools/v4/func: Exec format error`

**Expected behavior**
The npm package for the CLI tools should download (or build) a version of the tools for the relevant OS and CPU.

**Desktop (please complete the following information):**

- OS: Linux Mint 21.1 Cinnamon
- Version of SWA: latest from npm (i.e. running via npx)

**Additional context**

Logs:
```
npx @azure/static-web-apps-cli start --verbose=silly

Welcome to Azure Static Web Apps CLI (1.1.2)

Getting config file options from swa-cli.config.json...
Changed directory to /home/jaypratt/skfltech/skfl
Using configuration "skfl" from file:
  /home/jaypratt/skfltech/skfl/swa-cli.config.json

***********************************************************************
* WARNING: This emulator may not match the cloud environment exactly. *
* Always deploy and test your app in Azure.                           *
***********************************************************************

Checking if localhost:4280 is accepting TCP connections...
Port 4280 is available. Use it.
Resolved port number: 4280
appDevserverUrl provided, we will try connect to dev server at dist
Api Folder found: /home/jaypratt/skfltech/skfl/api
Trying to read workflow config with values:
 - appLocation: /home/jaypratt/skfltech/skfl
 - outputLocation: http://localhost:5173
 - apiLocation: /home/jaypratt/skfltech/skfl/api
Found a SWA workflow file: /home/jaypratt/skfltech/skfl/.github/workflows/azure-static-web-apps-lively-pond-0f8c8b91e.yml
 - app_build_command: <undefined>
 - api_build_command: <undefined>
 - app_location: /
 - output_location: dist
 - api_location: api
 - data_api_location: <undefined>
Validating user workflow config (BEFORE):
 - appLocation: /home/jaypratt/skfltech/skfl
 - outputLocation: http://localhost:5173
 - apiLocation: /home/jaypratt/skfltech/skfl/api
Validating user workflow config (AFTER):
 - appLocation: /home/jaypratt/skfltech/skfl
 - apiLocation: /home/jaypratt/skfltech/skfl/api
 - outputLocation: http://localhost:5173
 - dataApiLocation: <undefined>
Workflow configuration:
- config:
  - appBuildCommand: <undefined>
  - apiBuildCommand: <undefined>
  - appLocation: /home/jaypratt/skfltech/skfl
  - apiLocation: /home/jaypratt/skfltech/skfl/api
  - outputLocation: http://localhost:5173
  - dataApiLocation: <undefined>
 - files:
   - 0: /home/jaypratt/skfltech/skfl/.github/workflows/azure-static-web-apps-lively-pond-0f8c8b91e.yml
User workflow config:
 - appBuildCommand: <undefined>
 - apiBuildCommand: <undefined>
 - appLocation: /home/jaypratt/skfltech/skfl
 - apiLocation: /home/jaypratt/skfltech/skfl/api
 - outputLocation: http://localhost:5173
 - dataApiLocation: <undefined>
- files:
  - 0: /home/jaypratt/skfltech/skfl/.github/workflows/azure-static-web-apps-lively-pond-0f8c8b91e.yml
Running echo 'No Data API found'. Skipping
Starting the SWA emulator with the following configuration:
- ssl:
  - 0: false
  - 1: <undefined>
  - 2: <undefined>
- env:
  - SWA_RUNTIME_CONFIG_LOCATION: /home/jaypratt/skfltech/skfl
  - SWA_RUNTIME_WORKFLOW_LOCATION: /home/jaypratt/skfltech/skfl/.github/workflows/azure-static-web-apps-lively-pond-0f8c8b91e.yml
  - SWA_CLI_DEBUG: silly
  - SWA_CLI_API_PORT: 7071
  - SWA_CLI_APP_LOCATION: /home/jaypratt/skfltech/skfl
  - SWA_CLI_OUTPUT_LOCATION: http://localhost:5173
  - SWA_CLI_API_LOCATION: /home/jaypratt/skfltech/skfl/api
  - SWA_CLI_DATA_API_LOCATION: <undefined>
  - SWA_CLI_DATA_API_PORT: undefined
  - SWA_CLI_HOST: localhost
  - SWA_CLI_PORT: 4280
  - SWA_CLI_APP_SSL: false
  - SWA_CLI_APP_SSL_CERT: <undefined>
  - SWA_CLI_APP_SSL_KEY: <undefined>
  - SWA_CLI_STARTUP_COMMAND: npm run dev
  - SWA_CLI_VERSION: 1.1.2
  - SWA_CLI_SERVER_TIMEOUT: 60
  - SWA_CLI_OPEN_BROWSER: false
- commands:
  - swa: node "/home/jaypratt/skfltech/skfl/node_modules/@azure/static-web-apps-cli/dist/msha/server.js"
  - api: cd "/home/jaypratt/skfltech/skfl/api" && "/home/jaypratt/.swa/core-tools/v4/func" start --cors "*" --port 7071 
  - dataApi: <undefined>
  - run: cd "/home/jaypratt/skfltech/skfl" && npm run dev
[api] /bin/sh: 1: /home/jaypratt/.swa/core-tools/v4/func: Exec format error
[api] cd "/home/jaypratt/skfltech/skfl/api" && "/home/jaypratt/.swa/core-tools/v4/func" start --cors "*" --port 7071  exited with code 126
--> Sending SIGTERM to other processes..
[run] cd "/home/jaypratt/skfltech/skfl" && npm run dev exited with code SIGTERM
--> Sending SIGTERM to other processes..
[swa] node "/home/jaypratt/skfltech/skfl/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code SIGTERM
✖ SWA emulator stoped because SWA emulator exited with code SIGTERM.
```

**Comment by Cypher1** [comment]
Sorry, mixed up AMD and ARM. Updated comment and title

**Comment by Cypher1** [comment]
I attempted to use the `azure-cli` installation from https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt and this also failed (it seems `https://packages.microsoft.com/repos/azure-cli vera Release` does not have a release file).

Not sure how to proceed.

**Comment by Cypher1** [comment]
Hmm, removing the config file lets me use `swa start ./dist` but running with `swa ./dist --api-location api` fails.

It appears it is `~/.swa/core-tools/v4/func` that is the wrong format, not `swa` itself.

**Comment by kevinrs5855** [comment]
@Cypher1 , I think this is the same issue I am seeing, just tagging here to associate the bugs.

https://github.com/Azure/static-web-apps-cli/issues/703

**Comment by Cypher1** [comment]
Thanks @kevinrs5855 
Looks similar but for /Users/XXXX/.swa/dataApiBuilder/0.6.14/Microsoft.DataApiBuilder: cannot execute binary file rather thank the v4 API. Interesting. Not sure if the contributors will prefer to consider these separate or duplicate bugs. Keen to stay in contact about it though

**Comment by thomasgauvin** [comment]
Thanks for reporting this, we will investigate

**Comment by Cypher1** [comment]
Any news? We're keen to get started building with Azure. Would be nice to have at least an idea of the resolution path :)

**Comment by Cypher1** [comment]
Found a workaround. It seems that the issue was that swa was installing the azure-functions-core-tools itself and doing something wrong in the process.

We found that manually installing https://github.com/Azure/azure-functions-core-tools via the npm method bypassed this broken process and we were then able to run with the local api server AND the local server (which was previously).

Still learning how to get the two working together neatly (currently I'm coordinating the port numbers manually) but we're well on the way. Thanks for the tooling, looking forward to the out of box experience being as good as the dev experience (which I'm already enjoying).

Cheers

**Comment by Cypher1** [comment]
@nogic1008 Yup! We're hitting this now too. @thomasgauvin Any news?

**Comment by thomasgauvin** [comment]
The fix was found and awaiting release

**Comment by cjk7989** [comment]
The bugs on both azure-functions-core-tools and DataApiBuilder are caused by unzipping package "unzipper" with node 18. We are happy to inform you that we have released a new version that fixes the issue. Please update swa-cli to v1.1.4 and let us know if you encounter any problems.
