### ISSUE TITLE
Utilize az cli/managed identity credentials

### ISSUE THREAD

**Issue by onionhammer** [Azure/static-web-apps-cli#715]
swa login should be able to use the same credentials available to a managed identity (running on something like app service or azure container app), or azure CLI when using the SWA CLI locally 

"@azure/identity" is used here somewhere, but it seems to do this instead (from within a docker container)

swa login -u

```
Checking Azure session...
✖ Failed to setup project: Cannot autolaunch D-Bus without X11 $DISPLAY

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
```

**Comment by adrianhall** [comment]
#774 is merged and corrects this issue as well.
