### ISSUE TITLE
CLI not available on latest Docker image (1.1.3)

### ISSUE THREAD

**Issue by tnabil** [Azure/static-web-apps-cli#717]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When using the latest version of the Docker image (1.1.3), the swa command is not found.

**To Reproduce**

1. Run the docker image using `docker run --rm -p 4280:4280 -it swacli/static-web-apps-cli:latest`
2. Type in command 'swa --version'
3. You get the error `bash: swa: command not found`

**Expected behavior**
Expect to be able to run the `swa` command in the Docker container

**Screenshots**
![swa-error](https://github.com/Azure/static-web-apps-cli/assets/2771033/f6f8223c-d77e-4e10-91ac-eea6cc558a1e)

**Desktop (please complete the following information):**

- OS: Windows 10

- Version: 19045.3086

**Additional context**
This was run in WSL2

**Comment by cjk7989** [comment]
Hi @tnabil, sorry for the delayed response. swa-cli v1.1.4 has been released. You can use it in docker now.
