### ISSUE TITLE
No subscription found on asw deploy

### ISSUE THREAD

**Issue by Code-Divine** [Azure/static-web-apps-cli#727]
When I try to run asw deploy it shows tells me "No valid subscription found for tenant". But I do have Azure Sponsorship subscription for a fact and I have no issues working with azure cli.

If I specify the subscription id during login I get 

The access token is from the wrong issuer 'https://sts.windows.net/1131e-123123-123123-123-1231231/'. It must match the tenant 'https://sts.windows.net/234234-34234-234234-234234-234234234/' associated with this subscription. (ID's scrambled intentionally)

But that is even more confusing, I have only one azure account, one subscription, one tenant. I just registered with azure.

**Comment by Code-Divine** [comment]
Update. I solved it by providing both tenant id and subscription ID on login. But clearly the tool has some issue figuring out the tenant subscription.

**Comment by cjk7989** [comment]
Thanks for reporting. Could you run "swa login --verbose=silly" and provide a complete and detailed log with personal information removed? Also, could you try specifying tenant id by "--tenant-id" instead of "--subscription-id"?
