### ISSUE TITLE
Got error no valid subscription found for tenant

### ISSUE THREAD

**Issue by chengr4** [Azure/static-web-apps-cli#734]
I run `npx @azure/static-web-apps-cli login --no-use-keychain && npx @azure/static-web-apps-cli deploy` and got the error. 😢

> I followed the step from [PWA Starter](https://docs.pwabuilder.com/#/starter/publish?id=azure-static-web-apps). and used the dafault `swa-cli.config.json`

```json
{
  "$schema": "https://aka.ms/azure/static-web-apps-cli/schema",
  "configurations": {
    "pwa-starter": {
      "appLocation": ".",
      "outputLocation": "dist",
      "appBuildCommand": "npm run build --if-present",
      "run": "npm start",
      "appDevserverUrl": "http://localhost:3000"
    }
  }
}
```

**Expected behavior**

I expect to input my account/password to log into Azure

**Screenshots**

<img width="1255" alt="Screenshot 2023-07-26 at 4 59 58 PM" src="https://github.com/Azure/static-web-apps-cli/assets/54136390/4e6e77df-4528-4d71-a099-6248e106cf98">

**Additional context**

Maybe related to #727

**Comment by chengr4** [comment]
Update: I downgrade node version to v16.20.1 and it still does not work

**Comment by cjk7989** [comment]
The issue happened on the login step. Could you run "swa login --verbose=silly" and provide a complete and detailed log with personal information removed? Thanks!

**Comment by chengr4** [comment]
@cjk7989 Here you go
<img width="1377" alt="Screenshot 2023-07-31 at 2 42 38 PM" src="https://github.com/Azure/static-web-apps-cli/assets/54136390/2028a1dd-355c-4a83-b5df-a2b3fc09b1d7">

**Comment by cjk7989** [comment]
Could you first confirm if you have access to the subscription you want to use? If not, you can assign access to the identity corresponding to your tenant id. Then try to specify your subscription like "swa login --subscription-id=xxx  --verbose=silly" and see if it is ok.

**Comment by chengr4** [comment]
Hi,

I've manually deployed my app to the static app service, but I'm currently busy with other commitments. However, I will find a suitable time to assist with debugging the issue. If you believe the problem has been resolved, please feel free to close it.

if you think this issue can be closed temporarily, please close it. Thank you

**Comment by GitQuuu** [comment]
This issue has not been resolve i am having the same issue

**Comment by Nikhil4556** [comment]
@chengr4 could you tell me how have you deployed it manually. I am facing same issue and new to Azure Static WebApp.
Thanks in advance !

**Comment by chengr4** [comment]
Hi @Nikhil4556,
If I remember correctly, you create a Azure account and follow the instructions of static app service and you can make it

**Comment by PeerQu** [comment]
> Hi @Nikhil4556, If I remember correctly, you create a Azure account and follow the instructions of static app service and you can make it

Can you please clarify , there is a difference between Statis web app and App service - one is for pure frontend and the other for backend

**Comment by chengr4** [comment]
@PeerQu pure frontend

**Comment by jairusr** [comment]
I have solved the issue on my machine. The issue was that running az login wasn't logging me into the correct tenant.
By running the following you force it to log in to the tenant with access to the subscription.
`az login --tenant <tenant guid here>`

**Comment by chengr4** [comment]
Then here is a PR to make 🤪
