### ISSUE TITLE
Get Deploy Token

### ISSUE THREAD

**Issue by khill-fbmc** [Azure/static-web-apps-cli#750]
# Problem
I'm frustrated that the `deploy --print-token` command produces extraneous output

# Idea
Remove all extra output and print _just the token_

# Alternatives
[This is my current solution](https://gist.github.com/khill-fbmc/1dd4942738b019d41237704898ff40e6)

# Additional context

This is the code from the above link to save a click

```javascript
const { spawnSync } = require("node:child_process");

// Find the SWA CLI script
const binPath = require.resolve("@azure/static-web-apps-cli/dist/cli/bin.js");

// Run the script and capture the output
const { stdout } = spawnSync("node", [binPath, "deploy", "--print-token"], {
  stdio: "pipe",
});

// Remove empty lines from the output
const lines = `${stdout}`.split("\n").filter(Boolean);

// The last line is the token
const token = lines.pop();

process.stdout.write(token);
```

**Comment by gabynevada** [comment]
Or just ouput a json which is easier to parse, for now I'm using this:

```sh
swa deploy --print-token | awk '/Deployment token:/{getline; print}'
```

**Comment by adrianhall** [comment]
Are you explicitly wanting the deployment token via JavaScript, or command line?  I have code for both, but neither uses the SWA CLI.

**Comment by khill-fbmc** [comment]
To be honest, I don't need this anymore and have since moved on. Thank you.
