### ISSUE TITLE
Warning about workflow not found can be confusing

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#77]
**Describe the bug**
When there's no workflow file in the repo, the CLI prints a warning.

```
INFO: Azure Static Web Apps configuration not found under ".github/workflows/"
```

This might mislead the user to believe that a workflow is required. Suggest removing the message. Instead, show a message that config was loaded from the workflow (it's already doing this).

**Comment by anthonychu** [comment]
This seems to still be there.

**Comment by manekinekko** [comment]
I've made this accessible behind the `--verbose=info` flag. Which is not the default. 

The change is live in `main`
