### ISSUE TITLE
SWA dotnet 8.0 starter template 

### ISSUE THREAD

**Issue by eolamisan** [Azure/static-web-apps-cli#789]
I'm was frustrated will getting started with react and dotnet 7.0-8.0. 
All samples seem to be geared to towards Nodejs. 
Dotnet 8.0 deploying doesn't work at all with errors. 
Dotnet 7.0 deploys but the API is not working or even recognized. 

**Describe the solution you'd like**
A ready starter template deployable as website:
- react/angular/vuejs front end 
- dotnet 8.0 backed API 

**Describe alternatives you've considered**
I have used the swa cli and was able to get it to work locally. But deploying the API to Azure is just not working and no working example available. Stackoverflow  questions  regarding dotnet 7.0-8.0 missing answers. 

**Additional context**
Currently it seems this is not designed for dotnet developers. All samples seem to work for Nodejs. Even dotnet 7.0 doesn't work. Not to mention dotnet 8.0 which is in GA and LTS.

**Comment by aKzenT** [comment]
same issue here. the lack of any responses to issues in this repo is really disappointing.

**Comment by cjk7989** [comment]
Sorry for the delay. The dotnet-isolated version 8.0 for managed APIs has been supported via https://github.com/Azure/static-web-apps-cli/pull/809. For the issue that dotnet 7.0/8.0 doesn't work. Could you share an example for us to reproduce and investigate? Thanks!

**Comment by adrianhall** [comment]
9 months without response - main fix is in.  Closing.
