### ISSUE TITLE
 Failed to load staticwebapp.config.json schema. Continuing without validation!

### ISSUE THREAD

**Issue by madilkha** [Azure/static-web-apps-cli#805]
When using swa cli for the deployment to azure static web app with bitbecket pipeline, I got this error:

Deploying to environment: production
✖ Failed to load [staticwebapp.config.json](https://bitbucket.org/tkxel/signal-frontend/src/b9d282d1dd7801739b0496deca9f0d5e752b1c2e/staticwebapp.config.json) schema. Continuing without validation!

**Comment by itpropro** [comment]
Probably a duplicate of #802

**Comment by cjk7989** [comment]
Thanks for report! swa-cli@1.1.7 has been released and fixed this issue. So close it.

**Comment by madilkha** [comment]
Yes working now. thanks
