### ISSUE TITLE
Custom SWA roles don't work in Data API builder

### ISSUE THREAD

**Issue by itpropro** [Azure/static-web-apps-cli#807]
Custom roles (all except `authenticated` and `anonymous`) don't work with the Data API builder permission model and always return `AUTH_NOT_AUTHORIZED`.
Tested with identity provider `azureActiveDirectory` in swa config and authentication provider `StaticWebApps` in db config.

Duplicate of https://github.com/Azure/data-api-builder/issues/2074, as I don't know where this should be tracked.

**Comment by seantleonard** [comment]
Answer provided on other issue. Continuing conversation there.

> Hi @itpropro,
> 
> In your GraphQL request, make sure to include the HTTP header:
> `X-MS-API-ROLE` with value `custom-reader`
> 
> For more details with examples, see https://learn.microsoft.com/azure/data-api-builder/authorization#user-roles

**Comment by itpropro** [comment]
I hope my reply in the other issue explained why this is a bug and why it is not clear how it should be addressed, as regarding to your reply it can only be fixed by either fixing the SWA proxy to include the `X-MS-API-ROLE` header or to fix the parsing and usage of the `x-ms-client-principal` header in the data-api-builder project.
