### ISSUE TITLE
Deploy fails with no feedback, application is not deployed, stuck in "Uploading" forever

### ISSUE THREAD

**Issue by Peter-Juhasz** [Azure/static-web-apps-cli#816]
**Describe the bug**

Deploy fails with no feedback.

**To Reproduce**
```ps
swa deploy --deployment-token REDACTED
```

Output:
```
Welcome to Azure Static Web Apps CLI (1.1.7)

Deploying front-end files from folder:
  C:\REDACTED\dist

Consider providing api-language and version using --api-language and --api-version flags,
    otherwise default values apiLanguage: node and apiVersion: 16 will apply

Deploying to environment: preview

Deploying project to Azure Static Web Apps...
```

The CLI exits here without any other message, no error either.

Azure Portal shows "Uploading":

![image](https://github.com/Azure/static-web-apps-cli/assets/9047283/879162d3-9176-40de-a9c1-e2ea568a0e6b)

**Expected behavior**
Like any feedback from the app why it fails?

**Device info (if applicable):**
 - SWA: 1.1.7
 - OS: Windows 11 23H2 22631.3296
 - Node: 20.5.0

**Additional context**
The application is very simple, consists of an html file, and a css file.

The SWA resource was just created, completely new, there was nothing deployed earlier.

**Comment by lstorka** [comment]
Had the exact same problem and when I investigated the logs, one line that caught my eye:
ℹ Current directory cannot be identical to or contained within artifact folders.

So I just navigated one level up and then just run again:
`swa deploy --env production -V silly -a .\frontend`
and now it was successfully deployed 😃

**Comment by Peter-Juhasz** [comment]
@lstorka Thanks for the workaround! It worked!

**Comment by coder925** [comment]
The workaround works.

If you run the successful command but with `--dry-run` added you will see information still suggesting an error:
> i Could not get event info. Proceeding
> i The content server has rejected the request with: BadRequest
> i Reason: Missing request content.

Also, if you navigate up two directories:
`swa deploy --env production -a .\dist\frontend`
it stops working again. The CLI just returns to command prompt without writing the success message "Project deployed". No warning or errors are given.

**Comment by conradagramont** [comment]
Setting the variables in the config file and having the proper folder structure is key.  BTW, I'd recommend always running the cli with the --verbose silly switch.

I just wrapped up a blog post that could help shed some light on this.
[Using Azure Functions with Astro and Entra ID Authentication](https://agramont.net/blog/astro-entra-auth-azure-functions/#deploying-to-azure-using-swa-cli)

**Comment by JohanJimenex** [comment]
🤦‍♂️In my case it was because I had a "*" in a path in the "staticwebapp.config.json" file
```json
"routes": [
    {
      "route": "*",
      "allowedRoles": ["authenticated"]
    },
    ...
```

I replace it with :
 
```json
"routes": [
    {
      "route": "/",
      "allowedRoles": ["authenticated"]
    },
    ...
```

By the way, in the [documentation](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#restrict-access-to-entire-application) it says that we can use "/*" but this causes it to fail too

**Comment by adrianhall** [comment]
I see that this is now resolved - thanks for the community for jumping in!
