### ISSUE TITLE
Successfully logged into Azure! – Failed to setup project: EPERM: operation not permitted (Visual Studio Publishing)

### ISSUE THREAD

**Issue by SlimAhmad** [Azure/static-web-apps-cli#845]
Please can anyone help me out this stated after upgrading visual studio
Authenticating with Static Web Apps...
swa.cmd login --subscription-id 05684fd7-3bfe-4cc1-b4ad-ca41bcc98de1 --tenant-id a32d1fb1-51f6-435a-88f3-e44052f3e884 --app-name Pinkinetics --resource-group Pinkinetics --no-use-keychain
Welcome to Azure Static Web Apps CLI (1.1.8)
Checking Azure session...
✔ Successfully logged into Azure!
âœ– Failed to setup project: EPERM: operation not permitted, open 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\.env'
âœ– If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose

- Windows 11
- Blazor  wasm app

**Additional context**

**Comment by SlimAhmad** [comment]
The workaround was to use the cli (swa)  hope it helps

**Comment by adrianhall** [comment]
Dupe of #836
