### ISSUE TITLE
Hugo SWA Incorrectly Initializes swa-cli.config.json

### ISSUE THREAD

**Issue by Timothyw0** [Azure/static-web-apps-cli#856]
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
Following this tutorial here, while initializing the SWA, the swa-cli.config.json has incorrect parameters and missing the run and build commands. The detection code is not properly detecting the Hugo framework. 

**To Reproduce**
- Create an empty SWA
- Create a Hugo web app using `hugo new site swa-hugo-site`
- `cd swa-hugo-site`
- Initialize the SWA with `npx swa init --yes`
- Running `npx swa start` will not properly start the SWA

**Expected behavior**
The SWA should be started successfully after running `npx swa start`. The swa-cli.config.json should be:
```
{
  "$schema": "[https://aka.ms/azure/static-web-apps-cli/schema"](https://aka.ms/azure/static-web-apps-cli/schema%22),
  "configurations": {
    "swa-hugo-site": {
      "appLocation": ".",
      "outputLocation": "public",
      "run": "hugo server",
      "appDevserverUrl": "http://localhost:1313",
      "appBuildCommand": "hugo"
    }
  }
}
```

**Additional context**
The Hugo detection code is relying on finding a file named config.toml which may be from an older version, the new hugo command creates a hugo.toml file instead. We can just add this additional file lookup to the detection logic and should be set.

**Comment by adrianhall** [comment]
It should be noted that Hugo supports YAML, TOML or JSON.  See https://gohugo.io/getting-started/configuration/
