### ISSUE TITLE
Node.js 20 not supported

### ISSUE THREAD

**Issue by hlmnicholson** [Azure/static-web-apps-cli#864]
**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [ x] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
Node.js 20 is not supported - could this be updated?

<img width="646" alt="image" src="https://github.com/user-attachments/assets/76bea752-1178-4584-9443-69624dac3343">

**Desktop (please complete the following information):**

- OS: Sonoma
- Version 14.5

**Comment by adrianhall** [comment]
HI @hlmnicholson

Can you please comment with:

* Your full staticwebapp.config.json file
* Version of @azure/static-web-apps-cli you are using
* Version of Azure Functions Core Tools you are using

Thank you!
