### ISSUE TITLE
Cant login to Azure

### ISSUE THREAD

**Issue by domacikolaci** [Azure/static-web-apps-cli#879]
Hi, i am trying to login to Azure and keep getting the below error

`Welcome to Azure Static Web Apps CLI (2.0.1)

Using configuration "projectName" from file:
  /home/path/to/projectswa-cli.config.json

Checking Azure session...
✖ Failed to setup project: this.keychainCache.findCredentials is not a function

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose `

I also tried running swa login -S "sub ID for Azure" with no luck. I am on latest SWA version of 2.0.1

Any ideas? I am on Fedora 40 if this helps.

**Comment by CigarLu** [comment]
I had the same problem today.
I tried to install the Azure Cli
[Install the Azure CLI on Linux](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
and run `swa login` after running `az login`.

**Comment by akhil-lektik** [comment]
I am getting same issue. Any fix yet? I am on windows

**Comment by domacikolaci** [comment]
Thanks @CigarLu , this fixed my issue.
