### ISSUE TITLE
--api flag not respected in Windows Powershell terminal

### ISSUE THREAD

**Issue by nturinski** [Azure/static-web-apps-cli#88]
**Describe the bug**
Whenever I run `swa start .\frontend\build --api .\api` from the root of this repo https://github.com/microsoft/vscode-azureappservice/issues, it echoes `No API found. Skipping`.   I've confirmed that this works on MacOS and I have Func Core CLI tools v3.0.3284 installed

**To Reproduce**
1. Clone and npm install/npm build project https://github.com/microsoft/vscode-azureappservice/issues
2. From root, run command `swa start .\frontend\build --api .\api`
3. API not found error

**Expected behavior**
For the API folder to be recognized and start running the func core tools

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by manekinekko** [comment]
Thank you @nturinski for opening this issue. @aaronpowell is already looking at this.

**Comment by aaronpowell** [comment]
This should be fixed with #71, specifically https://github.com/Azure/static-web-apps-cli/pull/71/commits/b5b935b0072c754df7f5394cd03d68c597d76202

**Comment by itpropro** [comment]
This can be closed, as I have no problems with Windows Terminal 1.5 running PowerShell 7.1 on Windows 10 x64. I use the following syntax and it works fine:

```PowerShell
swa start http://localhost:3000 --api http://localhost:7071
```
![image](https://user-images.githubusercontent.com/15030951/110670746-0742da80-81ce-11eb-945a-9773b26a4abd.png)

You can also add --app for the first parameter, but as it's the default one, this works just as expected.

**Comment by manekinekko** [comment]
Thank you for the feedback @itpropro !

@nturinski would you mind trying running the CLI from the `main` branch? we've made some recent changes that might have fixed your issue.

**Comment by nturinski** [comment]
I can confirm that this is working! Thanks for all the hard work

![image](https://user-images.githubusercontent.com/5290572/110847203-7c132480-8261-11eb-81c7-93fa0966a0db.png)

One thing that's missing from the stable release though is the app alerting you to where it is available, which I thought was a useful touch.

![image](https://user-images.githubusercontent.com/5290572/110847799-360a9080-8262-11eb-9e8b-2295fdade6df.png)

**Comment by manekinekko** [comment]
Thank you @nturinski for the feedback. We have a whole user story for logging information to the console. I will make sure we add your feedback.

I am going to close this issue (fix landed in main).
