### ISSUE TITLE
Error when deploy Static Web Site

### ISSUE THREAD

**Issue by rsaldanha-sbp** [Azure/static-web-apps-cli#881]
Welcome to Azure Static Web Apps CLI (2.0.1)

Deploying front-end files from folder:
  C:\azure-devops\agent\_work\8\a\SBP.Portal.UI.1.0.7201-azure

Consider providing api-language and version using --api-language and --api-version flags,
    otherwise default values apiLanguage: node and apiVersion: 16 will apply

Deploying to environment: production

Deploying project to Azure Static Web Apps...
StaticSitesClient is outdated! Expected 216ea3f5dac3fc8be88ef78791ee0a0b4fed8922, got 1.0.026911
- Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
[swa] × Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
✖ 
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
Deployed!
##[error]PowerShell exited with code '1'.

**Comment by jjernberg** [comment]
This is the same issue I am encountering currently.   Each url is resulting in BlobNotFound.

```
Deploying project to Azure Static Web Apps...
Could not find StaticSitesClient local binary
Fetching release metadata for version: stable. Please wait...
GET https://swalocaldeploy.azureedge.net/downloads/versions.json
Decode JSON: [
  {
    "version": "latest",
    "buildId": "216ea3f5dac3fc8be88ef78791ee0a0b4fed8922",
    "publishDate": "2024-07-29T20:52:19.8593736Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient",
        "sha": "109f31a72efd311a8e38975fc97a51be8a610f799039ee27a457ff70ba00b496"
      },
      "win-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe",
        "sha": "4794453649a59b7d36fcaeee52e5328101c4fbf9821e721a90e40cbc3eb78dc6"
      },
      "osx-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient",
        "sha": "c9223197286457f17db70a620707135794e25b64f9420fcaea0663d4ed3b8e46"
      }
    }
  },
  {
    "version": "stable",
    "buildId": "216ea3f5dac3fc8be88ef78791ee0a0b4fed8922",
    "publishDate": "2024-07-29T20:52:19.8593736Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient",
        "sha": "109f31a72efd311a8e38975fc97a51be8a610f799039ee27a457ff70ba00b496"
      },
      "win-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe",
        "sha": "4794453649a59b7d36fcaeee52e5328101c4fbf9821e721a90e40cbc3eb78dc6"
      },
      "osx-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient",
        "sha": "c9223197286457f17db70a620707135794e25b64f9420fcaea0663d4ed3b8e46"
      }
    }
  },
  {
    "version": "backup",
    "buildId": "1.0.026792",
    "publishDate": "2024-05-03T18:31:36.0288058Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.026792/linux/StaticSitesClient",
        "sha": "a9dcd998d22a3476fb97fe1c446e83cc7f060a3a36cdb6757b828d0facc42347"
      },
      "win-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.026792/windows/StaticSitesClient.exe",
        "sha": "15f03e3f91208db2ea4015c4fce0623a692da1a289f23a782578ab7bc8a810e2"
      },
      "osx-x64": {
        "url": "https://swalocaldeploy.azureedge.net/downloads/1.0.026792/macOS/StaticSitesClient",
        "sha": "454b10f0351694ec3475a3d85b8746356932b2061a5be7e7fc093a6509cf000c"
      }
    }
  }
]
Release Metadata for stable: {
  "version": "stable",
  "buildId": "216ea3f5dac3fc8be88ef78791ee0a0b4fed8922",
  "publishDate": "2024-07-29T20:52:19.8593736Z",
  "files": {
    "linux-x64": {
      "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient",
      "sha": "109f31a72efd311a8e38975fc97a51be8a610f799039ee27a457ff70ba00b496"
    },
    "win-x64": {
      "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe",
      "sha": "4794453649a59b7d36fcaeee52e5328101c4fbf9821e721a90e40cbc3eb78dc6"
    },
    "osx-x64": {
      "url": "https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient",
      "sha": "c9223197286457f17db70a620707135794e25b64f9420fcaea0663d4ed3b8e46"
    }
  }
}
[swa] ✖ Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
✖ 
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
  ```

**Comment by paul-walls** [comment]
Just seconding this. It appears the https://swalocaldeploy.azureedge.net/downloads container is gone.

**Comment by anthonyvia** [comment]
We are also seeing this issue. Exact error for us:
```
- Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
[swa] ✖ Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
✖ 
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/linux/StaticSitesClient. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
```

**Comment by dlauterbach** [comment]
I am getting same error:
Deploying project to Azure Static Web Apps...
StaticSitesClient is outdated! Expected 216ea3f5dac3fc8be88ef78791ee0a0b4fed8922, got 1.0.026911

, stderr: - Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
[swa] ✖ Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
✖
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/
✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose

**Comment by YozoraRoy** [comment]
I encountered the same error here, and every site that was previously deployed successfully now shows this error:
StaticSitesClient is outdated! Expected 216ea3f5dac3fc8be88ef78791ee0a0b4fed8922, got 1.0.026911

[swa] × Downloading https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe@216ea3f5dac3fc8be88ef78791ee0a0b4fed8922
✖
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/windows/StaticSitesClient.exe. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/

✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose

**Comment by cjk7989** [comment]
> Here's a workaround for anyone who is trying to publish but are stuck on this issue:
> 
> 1. Go to whereever you have the swa client npm packages installed. On my windows machine, it was C:\Users\{USERNAME}\AppData\Roaming\npm\node_modules\
> 2. Go to @Azure\static-web-apps-cli\dist\core
> 3. Edit the `deploy-client.js` file
> 4. Add the following edit (at line 30):
> 
> Change:
> 
> ```
> const localBuildId = localClientMetadata.metadata.buildId;
> if (remoteBuildId === localBuildId) {
> ```
> 
> To:
> 
> ```
> const localBuildId = localClientMetadata.metadata.buildId;
> 
> return {
>     binary: localClientMetadata.binary,
>     buildId: localBuildId,
> };
> 
> if (remoteBuildId === localBuildId) {
> ```

Hi all, the website to download StaticSiteClient.exe was down, which caused the issue. We recommend applying this code change mentioned by @paul-walls to your local swa-cli repository. This will force swa-cli to use the local version of StaticSiteClient.exe that was downloaded during previous deployments.

If it still does not work, you can consider deploying via the Azure portal instead of swa-cli.
[Quickstart: Build your first static web app | Microsoft Learn](https://learn.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript&pivots=github)
[Create Static Web App - Microsoft Azure](https://ms.portal.azure.com/#create/Microsoft.StaticApp)

The fix will be released soon. Hope that helps.

**Comment by UddeshJain** [comment]
I'm getting same error. 

```
✖ Deployment Failed :(
✖ Deployment Failure Reason: Failed to download StaticSitesClient binary from url https://swalocaldeploy.azureedge.net/downloads/216ea3f5dac3fc8be88ef78791ee0a0b4fed8922/macOS/StaticSitesClient. File not found (404)
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/
```

**Comment by stefanello57** [comment]
I have the same issue and are not able to deploy

**Comment by boernard** [comment]
> Here's a workaround for anyone who is trying to publish but are stuck on this issue:
> 
>     1. Go to whereever you have the swa client npm packages installed. On my windows machine, it was C:\Users\{USERNAME}\AppData\Roaming\npm\node_modules\
> 
>     2. Go to @Azure\static-web-apps-cli\dist\core
> 
>     3. Edit the `deploy-client.js` file
> 
>     4. Add the following edit (at line 30):
> 
> 
> Change:
> 
> ```
> const localBuildId = localClientMetadata.metadata.buildId;
> if (remoteBuildId === localBuildId) {
> ```
> 
> To:
> 
> ```
> const localBuildId = localClientMetadata.metadata.buildId;
> 
> return {
>     binary: localClientMetadata.binary,
>     buildId: localBuildId,
> };
> 
> if (remoteBuildId === localBuildId) {
> ```

Thank you, this works.
Sometimes I am amazed how Microsoft manages to fuck things up for their customers.

**Comment by mkarmark** [comment]
We apologize for the inconvenience, we have mitigated the issue, do you mind confirming that you are unblocked?

**Comment by lw1321** [comment]
> > Here's a workaround for anyone who is trying to publish but are stuck on this issue:
> > 
> > 1. Go to whereever you have the swa client npm packages installed. On my windows machine, it was C:\Users{USERNAME}\AppData\Roaming\npm\node_modules\
> > 2. Go to @Azure\static-web-apps-cli\dist\core
> > 3. Edit the `deploy-client.js` file
> > 4. Add the following edit (at line 30):
> > 
> > Change:
> > ```
> > const localBuildId = localClientMetadata.metadata.buildId;
> > if (remoteBuildId === localBuildId) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To:
> > ```
> > const localBuildId = localClientMetadata.metadata.buildId;
> > 
> > return {
> >     binary: localClientMetadata.binary,
> >     buildId: localBuildId,
> > };
> > 
> > if (remoteBuildId === localBuildId) {
> > ```
> 
> Hi all, the website to download StaticSiteClient.exe was down, which caused the issue. We recommend applying this code change mentioned by @paul-walls to your local swa-cli repository. This will force swa-cli to use the local version of StaticSiteClient.exe that was downloaded during previous deployments.
> 
> If it still does not work, you can consider deploying via the Azure portal instead of swa-cli. [Quickstart: Build your first static web app | Microsoft Learn](https://learn.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript&pivots=github) [Create Static Web App - Microsoft Azure](https://ms.portal.azure.com/#create/Microsoft.StaticApp)
> 
> The fix will be released soon. Hope that helps.

With github actions and gitHub-hosted runners the workaround isn't working, as there is no StaticSiteClient on my local machine. Any ideas apart from moving away from swa-cli here?

**Comment by cjk7989** [comment]
> > > Here's a workaround for anyone who is trying to publish but are stuck on this issue:
> > > 
> > > 1. Go to whereever you have the swa client npm packages installed. On my windows machine, it was C:\Users{USERNAME}\AppData\Roaming\npm\node_modules\
> > > 2. Go to @Azure\static-web-apps-cli\dist\core
> > > 3. Edit the `deploy-client.js` file
> > > 4. Add the following edit (at line 30):
> > > 
> > > Change:
> > > ```
> > > const localBuildId = localClientMetadata.metadata.buildId;
> > > if (remoteBuildId === localBuildId) {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > To:
> > > ```
> > > const localBuildId = localClientMetadata.metadata.buildId;
> > > 
> > > return {
> > >     binary: localClientMetadata.binary,
> > >     buildId: localBuildId,
> > > };
> > > 
> > > if (remoteBuildId === localBuildId) {
> > > ```
> > 
> > 
> > Hi all, the website to download StaticSiteClient.exe was down, which caused the issue. We recommend applying this code change mentioned by @paul-walls to your local swa-cli repository. This will force swa-cli to use the local version of StaticSiteClient.exe that was downloaded during previous deployments.
> > If it still does not work, you can consider deploying via the Azure portal instead of swa-cli. [Quickstart: Build your first static web app | Microsoft Learn](https://learn.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript&pivots=github) [Create Static Web App - Microsoft Azure](https://ms.portal.azure.com/#create/Microsoft.StaticApp)
> > The fix will be released soon. Hope that helps.
> 
> With github actions and gitHub-hosted runners the workaround isn't working, as there is no StaticSiteClient on my local machine. Any ideas apart from moving away from swa-cli here?

The issue should have been fixed. Could you revert this code change, and try to deploy again? Thanks!

**Comment by lw1321** [comment]
hey @cjk7989, 
 Yes I can confirm it works again, thanks for the quick fix ;)

**Comment by dlauterbach** [comment]
> We apologize for the inconvenience, we have mitigated the issue, do you mind confirming that you are unblocked?

It is working for me now also.  Thank you!

**Comment by kevinsar** [comment]
Confirmed that this is working again, was failing last night about 12 hours ago and working again this morning without any changes 👍

**Comment by JacobWeyer** [comment]
I'm unblocked

**Comment by JmooreOsirs** [comment]
this solution worked for me as well. Thanks for the quick input @lw1321
