### ISSUE TITLE
Run app with inspect/debug opened

### ISSUE THREAD

**Issue by nturinski** [Azure/static-web-apps-cli#89]
**Is your feature request related to a problem? Please describe.**
For users to locally debug while running the local emulator, we'll need to expose the ports for debugging/inspecting.

**Describe the solution you'd like**
I think that for node.js, this should just be running the node process with the inspect flag and specify a port.  For C#, we'll have to attach to the process via processId.

**Additional context**
I'm working on the [Static Web Apps Extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestaticwebapps) and a core scenario for users is to run the emulator locally and then debug via VS Code.  The emulator has been awesome so far! 🎉

**Comment by manekinekko** [comment]
Thank you @nturinski for opening this feature request.

@anthonychu do we have the bandwidth to add this feature before GA?

**Comment by manekinekko** [comment]
@nturinski would the following work for your needs?

```
NODE_OPTIONS="--inspect" swa start ./dist/angular-auth0-swa
```

The trick here is to use the standard `NODE_OPTIONS` flags to pass arguments to the node.js process.

Let me know if that's an option for you, and I will add few check in the CLI to make sure this will work as expected.

**Comment by nturinski** [comment]
I think that this would work for us.  When we write a VS Code launch.json, we have the freedom to write the task however we want.  I think at that point, we can just attach the debugger and inspect like we would a normal node app.

**Comment by anthonychu** [comment]
For a frontend app, my understanding is that we should be attaching to the browser as that's where the code will be executing. There's no user code executing in the emulator (or the http server used by the emulator).

Here's a config I've been using that does what I think we want to do when debugging a SWA locally: 
https://github.com/anthonychu/swa-cli-js-sample/blob/78ae6b476cb675437fa2ce2cb54404cf78bc7d89/.vscode/launch.json

**Comment by anthonychu** [comment]
If you want to see how this works, we gave a sneak peek of the CLI in the Azure Functions webcast today: https://youtu.be/xEYQBPo11iI?t=2495

**Comment by nturinski** [comment]
Oh, I think Anthony is totally right on that.  Looks like I have everything that I would need to create the local experience in VS Code.  Sorry about that, that was my misunderstanding.

Thanks for this @anthonychu, this is extremely helpful

**Comment by manekinekko** [comment]
I am also sorry @nturinski I completely misunderstood your initial request. I thought you were looking to debug the actual CLI code itself 😅

+1 for what @anthonychu suggested!

**Comment by nturinski** [comment]
I'll go ahead and close this issue then.  Thanks again☺
