### ISSUE TITLE
Prominently display the emulator URL at startup

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#94]
Prominently display the emulator URL at startup. Currently the ports used by auth server and others are also printed, so we need to make the actual emulator port stand out.

**Comment by manekinekko** [comment]
I suggest using the [chalk package](https://www.npmjs.com/package/chalk) for that.

**Comment by manekinekko** [comment]
Related #111

**Comment by manekinekko** [comment]
Closed in #111
